linters:
  enable-all: true
  disable:
  - cyclop
  - gocognit
  - dogsled
  - errorlint
  - exhaustivestruct
  - exhaustruct
  - funlen
  - importas
  - interfacer
  - ireturn
  - gochecknoglobals
  - gochecknoinits
  - godot
  - maintidx
  - maligned
  - nlreturn
  - nosnakecase
  - paralleltest
  - prealloc
  - predeclared
  - scopelint
  - tagliatelle
  - varnamelen
  - wsl

  # Consider enabling
  - gocyclo
  - wrapcheck

  # Usually disabled but useful for checking everything has godoc
  - golint

linters-settings:
  gci:
    sections:
    - standard
    - default
    - prefix(github.com/myshkin5/moqueries)
  revive:
    rules:
    - name: var-naming
      arguments:
      - ["ID"]
  stylecheck:
    dot-import-whitelist:
    - "github.com/myshkin5/moqueries/ast"
    initialisms:
    - "-ID"

issues:
  exclude-use-default: false
  exclude-rules:
  - path: '(.+)_test.go'
    linters:
    - goconst
    - goerr113
  # No easy way to break up go:generate lines
  - linters:
    - lll
    source: "^//go:generate "
  include:
  # disable excluding of issues about comments from golint.
  - EXC0002
