linters:
  enable-all: true
  disable:
  - cyclop
  - gocognit
  - dogsled
  - errorlint
  - exhaustivestruct
  - funlen
  - importas
  - interfacer
  - ireturn
  - gochecknoglobals
  - gochecknoinits
  - godot
  - maintidx
  - maligned
  - nlreturn
  - paralleltest
  - prealloc
  - varnamelen
  - scopelint
  - wsl

  # Consider enabling
  - gocyclo
  - golint
  - wrapcheck

linters-settings:
  gci:
    local-prefixes: github.com/myshkin5/moqueries
  revive:
    rules:
    - name: var-naming
      arguments:
      - ["ID"]
  stylecheck:
    dot-import-whitelist:
    - "github.com/myshkin5/moqueries/ast"
    initialisms:
    - "-ID"

issues:
  exclude-rules:
  - path: '(.+)_test.go'
    linters:
    - goconst
    - goerr113
