linters:
  enable-all: true
  disable:
  - cyclop
  - gocognit
  - dogsled
  - errorlint
  - exhaustivestruct
  - exhaustruct
  - funlen
  - importas
  - interfacer
  - ireturn
  - gochecknoglobals
  - gochecknoinits
  - godot
  - maintidx
  - maligned
  - nlreturn
  - paralleltest
  - prealloc
  - predeclared
  - varnamelen
  - scopelint
  - wsl

  # Consider enabling
  - gocyclo
  - golint
  - wrapcheck

linters-settings:
  gci:
    sections:
    - standard
    - default
    - prefix(github.com/myshkin5/moqueries)
  revive:
    rules:
    - name: var-naming
      arguments:
      - ["ID"]
  stylecheck:
    dot-import-whitelist:
    - "github.com/myshkin5/moqueries/ast"
    initialisms:
    - "-ID"

issues:
  exclude-rules:
  - path: '(.+)_test.go'
    linters:
    - goconst
    - goerr113
  # No easy way to break up go:generate lines
  - linters:
    - lll
    source: "^//go:generate "
  # Inline nolint directive isn't working (CI/CD fails on nolintlint)
  - linters:
    - thelper
    # This is the actual test so not a helper
    path: 'generator/testmoqs/testmoqs_test.go'
    source: "testOptionalSuccess := func"
