version: "2"
linters:
  default: all
  disable:
  - cyclop
  - depguard
  - dogsled
  - errorlint
  - exhaustruct
  - funlen
  - importas
  - ireturn
  - gochecknoglobals
  - gochecknoinits
  - gocognit
  - goconst
  - godot
  - maintidx
  - nlreturn
  - paralleltest
  - prealloc
  - predeclared
  - tagliatelle
  - varnamelen
  - wsl

  # Consider enabling
  - gocyclo
  - wrapcheck

  settings:
    revive:
      rules:
      - name: var-naming
        disabled: true
    stylecheck:
      dot-import-whitelist:
      - "moqueries.org/cli/ast"
      initialisms:
      - "-ID"

  exclusions:
    paths:
    - ^testit.*
    - ^wordler.*
    presets:
    - comments
    - common-false-positives
    - legacy
    - std-error-handling
    rules:
    - path: '(.+)_test.go'
      linters:
      - err113
      - forcetypeassert
      - goconst
      - gocritic
      - goerr113
      - nestif
    # No easy way to break up go:generate lines
    - linters:
      - lll
      source: "^//go:generate "
    - path: 'testpkg'
      linters:
      - deadcode
      - revive
      - stylecheck
      - unused
    - linters:
      - unused
      path: generator/testmoqs/fnadaptors_test.go
    - linters:
      - unused
      path: generator/testmoqs/usualadaptors_test.go
    - linters:
      - inamedparam
      path: .*/testmoqs/.*
    - linters:
      - err113
      text: do not define dynamic errors
    - linters:
      - staticcheck
      text: "ST1001:"

formatters:
  settings:
    gci:
      sections:
      - standard
      - default
      - prefix(moqueries.org/cli)

