// Code generated by Moqueries - https://github.com/myshkin5/moqueries - DO NOT EDIT!

package testmocks_test

import (
	"sync/atomic"

	"github.com/myshkin5/moqueries/pkg/config"
	"github.com/myshkin5/moqueries/pkg/generator/testmocks"
	"github.com/myshkin5/moqueries/pkg/testing"
)

// mockNoParamsFn holds the state of a mock of the NoParamsFn type
type mockNoParamsFn struct {
	t               testing.MoqT
	config          config.MockConfig
	resultsByParams map[mockNoParamsFn_params]*mockNoParamsFn_resultMgr
	params          chan mockNoParamsFn_params
}

// mockNoParamsFn_mock isolates the mock interface of the NoParamsFn type
type mockNoParamsFn_mock struct {
	mock *mockNoParamsFn
}

// mockNoParamsFn_recorder isolates the recorder interface of the NoParamsFn type
type mockNoParamsFn_recorder struct {
	mock *mockNoParamsFn
}

// mockNoParamsFn_params holds the params of the NoParamsFn type
type mockNoParamsFn_params struct{}

// mockNoParamsFn_resultMgr manages multiple results and the state of the NoParamsFn type
type mockNoParamsFn_resultMgr struct {
	results  []*mockNoParamsFn_results
	index    uint32
	anyTimes bool
}

// mockNoParamsFn_results holds the results of the NoParamsFn type
type mockNoParamsFn_results struct {
	sResult string
	err     error
}

// mockNoParamsFn_fnRecorder routes recorded function calls to the mockNoParamsFn mock
type mockNoParamsFn_fnRecorder struct {
	params  mockNoParamsFn_params
	results *mockNoParamsFn_resultMgr
	mock    *mockNoParamsFn
}

// newMockNoParamsFn creates a new mock of the NoParamsFn type
func newMockNoParamsFn(t testing.MoqT, c *config.MockConfig) *mockNoParamsFn {
	if c == nil {
		c = &config.MockConfig{}
	}
	return &mockNoParamsFn{
		t:               t,
		config:          *c,
		resultsByParams: map[mockNoParamsFn_params]*mockNoParamsFn_resultMgr{},
		params:          make(chan mockNoParamsFn_params, 100),
	}
}

// mock returns the mock implementation of the NoParamsFn type
func (m *mockNoParamsFn) mock() testmocks.NoParamsFn {
	return func() (sResult string, err error) { mock := &mockNoParamsFn_mock{mock: m}; return mock.fn() }
}

func (m *mockNoParamsFn_mock) fn() (sResult string, err error) {
	params := mockNoParamsFn_params{}
	m.mock.params <- params
	results, ok := m.mock.resultsByParams[params]
	if !ok {
		if m.mock.config.Expectation == config.Strict {
			m.mock.t.Fatalf("Unexpected call with parameters %#v", params)
		}
		return
	}

	i := int(atomic.AddUint32(&results.index, 1)) - 1
	if i >= len(results.results) {
		if !results.anyTimes {
			if m.mock.config.Expectation == config.Strict {
				m.mock.t.Fatalf("Too many calls to mock with parameters %#v", params)
			}
			return
		}
		i = len(results.results) - 1
	}
	result := results.results[i]
	sResult = result.sResult
	err = result.err
	return
}

func (m *mockNoParamsFn) onCall() *mockNoParamsFn_fnRecorder {
	return &mockNoParamsFn_fnRecorder{
		params: mockNoParamsFn_params{},
		mock:   m,
	}
}

func (r *mockNoParamsFn_fnRecorder) returnResults(sResult string, err error) *mockNoParamsFn_fnRecorder {
	if r.results == nil {
		if _, ok := r.mock.resultsByParams[r.params]; ok {
			r.mock.t.Fatalf("Expectations already recorded for mock with parameters %#v", r.params)
			return nil
		}

		r.results = &mockNoParamsFn_resultMgr{results: []*mockNoParamsFn_results{}, index: 0, anyTimes: false}
		r.mock.resultsByParams[r.params] = r.results
	}
	r.results.results = append(r.results.results, &mockNoParamsFn_results{
		sResult: sResult,
		err:     err,
	})
	return r
}

func (r *mockNoParamsFn_fnRecorder) times(count int) *mockNoParamsFn_fnRecorder {
	if r.results == nil {
		r.mock.t.Fatalf("Return must be called before calling Times")
		return nil
	}
	last := r.results.results[len(r.results.results)-1]
	for n := 0; n < count-1; n++ {
		r.results.results = append(r.results.results, last)
	}
	return r
}

func (r *mockNoParamsFn_fnRecorder) anyTimes() {
	if r.results == nil {
		r.mock.t.Fatalf("Return must be called before calling AnyTimes")
		return
	}
	r.results.anyTimes = true
}
