version: 2.1

executors:
  go:
    docker:
    - image: circleci/golang:1.17

jobs:
  build:

    environment:
      TEST_RESULTS: /tmp/test-results

    executor: go

    steps:
    - checkout
    - run: mkdir -p $TEST_RESULTS

    - restore_cache:
        keys:
        - go-mod-v4-{{ checksum "go.sum" }}

    - run:
        name: Generate code

        command: |
          go build -o $GOPATH/bin/moqueries github.com/myshkin5/moqueries
          go generate ./...
          # See https://github.com/myshkin5/moqueries/issues/7
          git restore moq/moq_testing.go

    - run:
        name: Run tests

        command: |
          PACKAGE_NAMES=$(go list ./... | circleci tests split --split-by=timings --timings-type=classname)
          gotestsum --junitfile ${TEST_RESULTS}/gotestsum-report.xml -- $PACKAGE_NAMES

    - run:
        name: Run code linters

        command: |
          GOLANGCI_LINT_VER=$(go list -m -f '{{.Version}}' github.com/golangci/golangci-lint)
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | \
            sh -s -- -b $(go env GOPATH)/bin "$GOLANGCI_LINT_VER"
          golangci-lint run

    - run:
        name: Check for dirty working directory

        command: |
          git status
          [[ -z $(git status --short) ]] || echo 'Untracked changes' && exit 1

    - save_cache:
        key: go-mod-v4-{{ checksum "go.sum" }}
        paths:
        - "/go/pkg/mod"

    - store_artifacts:
        path: /tmp/test-results
        destination: raw-test-output

    - store_test_results:
        path: /tmp/test-results

workflows:
  version: 2
  build-workflow:
    jobs:
    - build
