// Code generated by Moqueries - https://github.com/myshkin5/moqueries - DO NOT EDIT!

package exported

import (
	"math/bits"
	"sync/atomic"

	"github.com/myshkin5/moqueries/generator/testmoqs"
	"github.com/myshkin5/moqueries/hash"
	"github.com/myshkin5/moqueries/moq"
)

// MoqPassByReferenceFn holds the state of a moq of the PassByReferenceFn type
type MoqPassByReferenceFn struct {
	Scene  *moq.Scene
	Config moq.Config
	Moq    *MoqPassByReferenceFn_mock

	ResultsByParams []MoqPassByReferenceFn_resultsByParams

	Runtime struct {
		ParameterIndexing struct {
			P moq.ParamIndexing
		}
	}
}

// MoqPassByReferenceFn_mock isolates the mock interface of the PassByReferenceFn type
type MoqPassByReferenceFn_mock struct {
	Moq *MoqPassByReferenceFn
}

// MoqPassByReferenceFn_params holds the params of the PassByReferenceFn type
type MoqPassByReferenceFn_params struct {
	P *testmoqs.PassByReferenceParams
}

// MoqPassByReferenceFn_paramsKey holds the map key params of the PassByReferenceFn type
type MoqPassByReferenceFn_paramsKey struct {
	Params struct {
		P *testmoqs.PassByReferenceParams
	}
	Hashes struct{ P hash.Hash }
}

// MoqPassByReferenceFn_resultsByParams contains the results for a given set of parameters for the PassByReferenceFn type
type MoqPassByReferenceFn_resultsByParams struct {
	AnyCount  int
	AnyParams uint64
	Results   map[MoqPassByReferenceFn_paramsKey]*MoqPassByReferenceFn_results
}

// MoqPassByReferenceFn_doFn defines the type of function needed when calling AndDo for the PassByReferenceFn type
type MoqPassByReferenceFn_doFn func(p *testmoqs.PassByReferenceParams)

// MoqPassByReferenceFn_doReturnFn defines the type of function needed when calling DoReturnResults for the PassByReferenceFn type
type MoqPassByReferenceFn_doReturnFn func(p *testmoqs.PassByReferenceParams) (sResult string, err error)

// MoqPassByReferenceFn_results holds the results of the PassByReferenceFn type
type MoqPassByReferenceFn_results struct {
	Params  MoqPassByReferenceFn_params
	Results []struct {
		Values *struct {
			SResult string
			Err     error
		}
		Sequence   uint32
		DoFn       MoqPassByReferenceFn_doFn
		DoReturnFn MoqPassByReferenceFn_doReturnFn
	}
	Index  uint32
	Repeat *moq.RepeatVal
}

// MoqPassByReferenceFn_fnRecorder routes recorded function calls to the MoqPassByReferenceFn moq
type MoqPassByReferenceFn_fnRecorder struct {
	Params    MoqPassByReferenceFn_params
	AnyParams uint64
	Sequence  bool
	Results   *MoqPassByReferenceFn_results
	Moq       *MoqPassByReferenceFn
}

// MoqPassByReferenceFn_anyParams isolates the any params functions of the PassByReferenceFn type
type MoqPassByReferenceFn_anyParams struct {
	Recorder *MoqPassByReferenceFn_fnRecorder
}

// NewMoqPassByReferenceFn creates a new moq of the PassByReferenceFn type
func NewMoqPassByReferenceFn(scene *moq.Scene, config *moq.Config) *MoqPassByReferenceFn {
	if config == nil {
		config = &moq.Config{}
	}
	m := &MoqPassByReferenceFn{
		Scene:  scene,
		Config: *config,
		Moq:    &MoqPassByReferenceFn_mock{},

		Runtime: struct {
			ParameterIndexing struct {
				P moq.ParamIndexing
			}
		}{ParameterIndexing: struct {
			P moq.ParamIndexing
		}{
			P: moq.ParamIndexByHash,
		}},
	}
	m.Moq.Moq = m

	scene.AddMoq(m)
	return m
}

// Mock returns the moq implementation of the PassByReferenceFn type
func (m *MoqPassByReferenceFn) Mock() testmoqs.PassByReferenceFn {
	return func(p *testmoqs.PassByReferenceParams) (_ string, _ error) {
		moq := &MoqPassByReferenceFn_mock{Moq: m}
		return moq.Fn(p)
	}
}

func (m *MoqPassByReferenceFn_mock) Fn(p *testmoqs.PassByReferenceParams) (sResult string, err error) {
	params := MoqPassByReferenceFn_params{
		P: p,
	}
	var results *MoqPassByReferenceFn_results
	for _, resultsByParams := range m.Moq.ResultsByParams {
		paramsKey := m.Moq.ParamsKey(params, resultsByParams.AnyParams)
		var ok bool
		results, ok = resultsByParams.Results[paramsKey]
		if ok {
			break
		}
	}
	if results == nil {
		if m.Moq.Config.Expectation == moq.Strict {
			m.Moq.Scene.T.Fatalf("Unexpected call with parameters %#v", params)
		}
		return
	}

	i := int(atomic.AddUint32(&results.Index, 1)) - 1
	if i >= results.Repeat.ResultCount {
		if !results.Repeat.AnyTimes {
			if m.Moq.Config.Expectation == moq.Strict {
				m.Moq.Scene.T.Fatalf("Too many calls to mock with parameters %#v", params)
			}
			return
		}
		i = results.Repeat.ResultCount - 1
	}

	result := results.Results[i]
	if result.Sequence != 0 {
		sequence := m.Moq.Scene.NextMockSequence()
		if (!results.Repeat.AnyTimes && result.Sequence != sequence) || result.Sequence > sequence {
			m.Moq.Scene.T.Fatalf("Call sequence does not match %#v", params)
		}
	}

	if result.DoFn != nil {
		result.DoFn(p)
	}

	if result.Values != nil {
		sResult = result.Values.SResult
		err = result.Values.Err
	}
	if result.DoReturnFn != nil {
		sResult, err = result.DoReturnFn(p)
	}
	return
}

func (m *MoqPassByReferenceFn) OnCall(p *testmoqs.PassByReferenceParams) *MoqPassByReferenceFn_fnRecorder {
	return &MoqPassByReferenceFn_fnRecorder{
		Params: MoqPassByReferenceFn_params{
			P: p,
		},
		Sequence: m.Config.Sequence == moq.SeqDefaultOn,
		Moq:      m,
	}
}

func (r *MoqPassByReferenceFn_fnRecorder) Any() *MoqPassByReferenceFn_anyParams {
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("Any functions must be called before ReturnResults or DoReturnResults calls, parameters: %#v", r.Params)
		return nil
	}
	return &MoqPassByReferenceFn_anyParams{Recorder: r}
}

func (a *MoqPassByReferenceFn_anyParams) P() *MoqPassByReferenceFn_fnRecorder {
	a.Recorder.AnyParams |= 1 << 0
	return a.Recorder
}

func (r *MoqPassByReferenceFn_fnRecorder) Seq() *MoqPassByReferenceFn_fnRecorder {
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("Seq must be called before ReturnResults or DoReturnResults calls, parameters: %#v", r.Params)
		return nil
	}
	r.Sequence = true
	return r
}

func (r *MoqPassByReferenceFn_fnRecorder) NoSeq() *MoqPassByReferenceFn_fnRecorder {
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("NoSeq must be called before ReturnResults or DoReturnResults calls, parameters: %#v", r.Params)
		return nil
	}
	r.Sequence = false
	return r
}

func (r *MoqPassByReferenceFn_fnRecorder) ReturnResults(sResult string, err error) *MoqPassByReferenceFn_fnRecorder {
	r.FindResults()

	var sequence uint32
	if r.Sequence {
		sequence = r.Moq.Scene.NextRecorderSequence()
	}

	r.Results.Results = append(r.Results.Results, struct {
		Values *struct {
			SResult string
			Err     error
		}
		Sequence   uint32
		DoFn       MoqPassByReferenceFn_doFn
		DoReturnFn MoqPassByReferenceFn_doReturnFn
	}{
		Values: &struct {
			SResult string
			Err     error
		}{
			SResult: sResult,
			Err:     err,
		},
		Sequence: sequence,
	})
	return r
}

func (r *MoqPassByReferenceFn_fnRecorder) AndDo(fn MoqPassByReferenceFn_doFn) *MoqPassByReferenceFn_fnRecorder {
	if r.Results == nil {
		r.Moq.Scene.T.Fatalf("ReturnResults must be called before calling AndDo")
		return nil
	}
	last := &r.Results.Results[len(r.Results.Results)-1]
	last.DoFn = fn
	return r
}

func (r *MoqPassByReferenceFn_fnRecorder) DoReturnResults(fn MoqPassByReferenceFn_doReturnFn) *MoqPassByReferenceFn_fnRecorder {
	r.FindResults()

	var sequence uint32
	if r.Sequence {
		sequence = r.Moq.Scene.NextRecorderSequence()
	}

	r.Results.Results = append(r.Results.Results, struct {
		Values *struct {
			SResult string
			Err     error
		}
		Sequence   uint32
		DoFn       MoqPassByReferenceFn_doFn
		DoReturnFn MoqPassByReferenceFn_doReturnFn
	}{Sequence: sequence, DoReturnFn: fn})
	return r
}

func (r *MoqPassByReferenceFn_fnRecorder) FindResults() {
	if r.Results != nil {
		r.Results.Repeat.Increment(r.Moq.Scene.T)
		return
	}

	anyCount := bits.OnesCount64(r.AnyParams)
	insertAt := -1
	var results *MoqPassByReferenceFn_resultsByParams
	for n, res := range r.Moq.ResultsByParams {
		if res.AnyParams == r.AnyParams {
			results = &res
			break
		}
		if res.AnyCount > anyCount {
			insertAt = n
		}
	}
	if results == nil {
		results = &MoqPassByReferenceFn_resultsByParams{
			AnyCount:  anyCount,
			AnyParams: r.AnyParams,
			Results:   map[MoqPassByReferenceFn_paramsKey]*MoqPassByReferenceFn_results{},
		}
		r.Moq.ResultsByParams = append(r.Moq.ResultsByParams, *results)
		if insertAt != -1 && insertAt+1 < len(r.Moq.ResultsByParams) {
			copy(r.Moq.ResultsByParams[insertAt+1:], r.Moq.ResultsByParams[insertAt:0])
			r.Moq.ResultsByParams[insertAt] = *results
		}
	}

	paramsKey := r.Moq.ParamsKey(r.Params, r.AnyParams)

	var ok bool
	r.Results, ok = results.Results[paramsKey]
	if !ok {
		r.Results = &MoqPassByReferenceFn_results{
			Params:  r.Params,
			Results: nil,
			Index:   0,
			Repeat:  &moq.RepeatVal{},
		}
		results.Results[paramsKey] = r.Results
	}

	r.Results.Repeat.Increment(r.Moq.Scene.T)
}

func (r *MoqPassByReferenceFn_fnRecorder) Repeat(repeaters ...moq.Repeater) *MoqPassByReferenceFn_fnRecorder {
	if r.Results == nil {
		r.Moq.Scene.T.Fatalf("ReturnResults or DoReturnResults must be called before calling Repeat")
		return nil
	}
	r.Results.Repeat.Repeat(r.Moq.Scene.T, repeaters)
	last := r.Results.Results[len(r.Results.Results)-1]
	for n := 0; n < r.Results.Repeat.ResultCount-1; n++ {
		if r.Sequence {
			last = struct {
				Values *struct {
					SResult string
					Err     error
				}
				Sequence   uint32
				DoFn       MoqPassByReferenceFn_doFn
				DoReturnFn MoqPassByReferenceFn_doReturnFn
			}{
				Values: &struct {
					SResult string
					Err     error
				}{
					SResult: last.Values.SResult,
					Err:     last.Values.Err,
				},
				Sequence: r.Moq.Scene.NextRecorderSequence(),
			}
		}
		r.Results.Results = append(r.Results.Results, last)
	}
	return r
}

func (m *MoqPassByReferenceFn) ParamsKey(params MoqPassByReferenceFn_params, anyParams uint64) MoqPassByReferenceFn_paramsKey {
	var pUsed *testmoqs.PassByReferenceParams
	var pUsedHash hash.Hash
	if anyParams&(1<<0) == 0 {
		if m.Runtime.ParameterIndexing.P == moq.ParamIndexByValue {
			pUsed = params.P
		} else {
			pUsedHash = hash.DeepHash(params.P)
		}
	}
	return MoqPassByReferenceFn_paramsKey{
		Params: struct {
			P *testmoqs.PassByReferenceParams
		}{
			P: pUsed,
		},
		Hashes: struct{ P hash.Hash }{
			P: pUsedHash,
		}}
}

// Reset resets the state of the moq
func (m *MoqPassByReferenceFn) Reset() { m.ResultsByParams = nil }

// AssertExpectationsMet asserts that all expectations have been met
func (m *MoqPassByReferenceFn) AssertExpectationsMet() {
	for _, res := range m.ResultsByParams {
		for _, results := range res.Results {
			missing := results.Repeat.MinTimes - int(atomic.LoadUint32(&results.Index))
			if missing > 0 {
				m.Scene.T.Errorf("Expected %d additional call(s) with parameters %#v", missing, results.Params)
			}
		}
	}
}
