// Code generated by Moqueries - https://github.com/myshkin5/moqueries - DO NOT EDIT!

package generator_test

import (
	"math/bits"
	"sync/atomic"

	"github.com/dave/dst"
	"github.com/myshkin5/moqueries/pkg/generator"
	"github.com/myshkin5/moqueries/pkg/hash"
	"github.com/myshkin5/moqueries/pkg/moq"
)

// mockConverterer holds the state of a mock of the Converterer type
type mockConverterer struct {
	scene                             *moq.Scene
	config                            moq.MockConfig
	resultsByParams_BaseStruct        []mockConverterer_BaseStruct_resultsByParams
	resultsByParams_IsolationStruct   []mockConverterer_IsolationStruct_resultsByParams
	resultsByParams_MethodStructs     []mockConverterer_MethodStructs_resultsByParams
	resultsByParams_NewFunc           []mockConverterer_NewFunc_resultsByParams
	resultsByParams_IsolationAccessor []mockConverterer_IsolationAccessor_resultsByParams
	resultsByParams_FuncClosure       []mockConverterer_FuncClosure_resultsByParams
	resultsByParams_MockMethod        []mockConverterer_MockMethod_resultsByParams
	resultsByParams_RecorderMethods   []mockConverterer_RecorderMethods_resultsByParams
	resultsByParams_ResetMethod       []mockConverterer_ResetMethod_resultsByParams
	resultsByParams_AssertMethod      []mockConverterer_AssertMethod_resultsByParams
}

// mockConverterer_mock isolates the mock interface of the Converterer type
type mockConverterer_mock struct {
	mock *mockConverterer
}

// mockConverterer_recorder isolates the recorder interface of the Converterer type
type mockConverterer_recorder struct {
	mock *mockConverterer
}

// mockConverterer_BaseStruct_params holds the params of the Converterer type
type mockConverterer_BaseStruct_params struct {
	typeSpec *dst.TypeSpec
	funcs    []generator.Func
}

// mockConverterer_BaseStruct_paramsKey holds the map key params of the Converterer type
type mockConverterer_BaseStruct_paramsKey struct {
	typeSpec *dst.TypeSpec
	funcs    hash.Hash
}

// mockConverterer_BaseStruct_resultsByParams contains the results for a given set of parameters for the Converterer type
type mockConverterer_BaseStruct_resultsByParams struct {
	anyCount  int
	anyParams uint64
	results   map[mockConverterer_BaseStruct_paramsKey]*mockConverterer_BaseStruct_results
}

// mockConverterer_BaseStruct_doFn defines the type of function needed when calling andDo for the Converterer type
type mockConverterer_BaseStruct_doFn func(typeSpec *dst.TypeSpec, funcs []generator.Func)

// mockConverterer_BaseStruct_doReturnFn defines the type of function needed when calling doReturnResults for the Converterer type
type mockConverterer_BaseStruct_doReturnFn func(typeSpec *dst.TypeSpec, funcs []generator.Func) (structDecl *dst.GenDecl)

// mockConverterer_BaseStruct_results holds the results of the Converterer type
type mockConverterer_BaseStruct_results struct {
	params  mockConverterer_BaseStruct_params
	results []struct {
		values     *struct{ structDecl *dst.GenDecl }
		sequence   uint32
		doFn       mockConverterer_BaseStruct_doFn
		doReturnFn mockConverterer_BaseStruct_doReturnFn
	}
	index    uint32
	anyTimes bool
}

// mockConverterer_BaseStruct_fnRecorder routes recorded function calls to the mockConverterer mock
type mockConverterer_BaseStruct_fnRecorder struct {
	params    mockConverterer_BaseStruct_params
	paramsKey mockConverterer_BaseStruct_paramsKey
	anyParams uint64
	sequence  bool
	results   *mockConverterer_BaseStruct_results
	mock      *mockConverterer
}

// mockConverterer_IsolationStruct_params holds the params of the Converterer type
type mockConverterer_IsolationStruct_params struct{ typeName, suffix string }

// mockConverterer_IsolationStruct_paramsKey holds the map key params of the Converterer type
type mockConverterer_IsolationStruct_paramsKey struct{ typeName, suffix string }

// mockConverterer_IsolationStruct_resultsByParams contains the results for a given set of parameters for the Converterer type
type mockConverterer_IsolationStruct_resultsByParams struct {
	anyCount  int
	anyParams uint64
	results   map[mockConverterer_IsolationStruct_paramsKey]*mockConverterer_IsolationStruct_results
}

// mockConverterer_IsolationStruct_doFn defines the type of function needed when calling andDo for the Converterer type
type mockConverterer_IsolationStruct_doFn func(typeName, suffix string)

// mockConverterer_IsolationStruct_doReturnFn defines the type of function needed when calling doReturnResults for the Converterer type
type mockConverterer_IsolationStruct_doReturnFn func(typeName, suffix string) (structDecl *dst.GenDecl)

// mockConverterer_IsolationStruct_results holds the results of the Converterer type
type mockConverterer_IsolationStruct_results struct {
	params  mockConverterer_IsolationStruct_params
	results []struct {
		values     *struct{ structDecl *dst.GenDecl }
		sequence   uint32
		doFn       mockConverterer_IsolationStruct_doFn
		doReturnFn mockConverterer_IsolationStruct_doReturnFn
	}
	index    uint32
	anyTimes bool
}

// mockConverterer_IsolationStruct_fnRecorder routes recorded function calls to the mockConverterer mock
type mockConverterer_IsolationStruct_fnRecorder struct {
	params    mockConverterer_IsolationStruct_params
	paramsKey mockConverterer_IsolationStruct_paramsKey
	anyParams uint64
	sequence  bool
	results   *mockConverterer_IsolationStruct_results
	mock      *mockConverterer
}

// mockConverterer_MethodStructs_params holds the params of the Converterer type
type mockConverterer_MethodStructs_params struct {
	typeSpec *dst.TypeSpec
	fn       generator.Func
}

// mockConverterer_MethodStructs_paramsKey holds the map key params of the Converterer type
type mockConverterer_MethodStructs_paramsKey struct {
	typeSpec *dst.TypeSpec
	fn       generator.Func
}

// mockConverterer_MethodStructs_resultsByParams contains the results for a given set of parameters for the Converterer type
type mockConverterer_MethodStructs_resultsByParams struct {
	anyCount  int
	anyParams uint64
	results   map[mockConverterer_MethodStructs_paramsKey]*mockConverterer_MethodStructs_results
}

// mockConverterer_MethodStructs_doFn defines the type of function needed when calling andDo for the Converterer type
type mockConverterer_MethodStructs_doFn func(typeSpec *dst.TypeSpec, fn generator.Func)

// mockConverterer_MethodStructs_doReturnFn defines the type of function needed when calling doReturnResults for the Converterer type
type mockConverterer_MethodStructs_doReturnFn func(typeSpec *dst.TypeSpec, fn generator.Func) (structDecls []dst.Decl)

// mockConverterer_MethodStructs_results holds the results of the Converterer type
type mockConverterer_MethodStructs_results struct {
	params  mockConverterer_MethodStructs_params
	results []struct {
		values     *struct{ structDecls []dst.Decl }
		sequence   uint32
		doFn       mockConverterer_MethodStructs_doFn
		doReturnFn mockConverterer_MethodStructs_doReturnFn
	}
	index    uint32
	anyTimes bool
}

// mockConverterer_MethodStructs_fnRecorder routes recorded function calls to the mockConverterer mock
type mockConverterer_MethodStructs_fnRecorder struct {
	params    mockConverterer_MethodStructs_params
	paramsKey mockConverterer_MethodStructs_paramsKey
	anyParams uint64
	sequence  bool
	results   *mockConverterer_MethodStructs_results
	mock      *mockConverterer
}

// mockConverterer_NewFunc_params holds the params of the Converterer type
type mockConverterer_NewFunc_params struct{ typeSpec *dst.TypeSpec }

// mockConverterer_NewFunc_paramsKey holds the map key params of the Converterer type
type mockConverterer_NewFunc_paramsKey struct{ typeSpec *dst.TypeSpec }

// mockConverterer_NewFunc_resultsByParams contains the results for a given set of parameters for the Converterer type
type mockConverterer_NewFunc_resultsByParams struct {
	anyCount  int
	anyParams uint64
	results   map[mockConverterer_NewFunc_paramsKey]*mockConverterer_NewFunc_results
}

// mockConverterer_NewFunc_doFn defines the type of function needed when calling andDo for the Converterer type
type mockConverterer_NewFunc_doFn func(typeSpec *dst.TypeSpec)

// mockConverterer_NewFunc_doReturnFn defines the type of function needed when calling doReturnResults for the Converterer type
type mockConverterer_NewFunc_doReturnFn func(typeSpec *dst.TypeSpec) (funcDecl *dst.FuncDecl)

// mockConverterer_NewFunc_results holds the results of the Converterer type
type mockConverterer_NewFunc_results struct {
	params  mockConverterer_NewFunc_params
	results []struct {
		values     *struct{ funcDecl *dst.FuncDecl }
		sequence   uint32
		doFn       mockConverterer_NewFunc_doFn
		doReturnFn mockConverterer_NewFunc_doReturnFn
	}
	index    uint32
	anyTimes bool
}

// mockConverterer_NewFunc_fnRecorder routes recorded function calls to the mockConverterer mock
type mockConverterer_NewFunc_fnRecorder struct {
	params    mockConverterer_NewFunc_params
	paramsKey mockConverterer_NewFunc_paramsKey
	anyParams uint64
	sequence  bool
	results   *mockConverterer_NewFunc_results
	mock      *mockConverterer
}

// mockConverterer_IsolationAccessor_params holds the params of the Converterer type
type mockConverterer_IsolationAccessor_params struct{ typeName, suffix, fnName string }

// mockConverterer_IsolationAccessor_paramsKey holds the map key params of the Converterer type
type mockConverterer_IsolationAccessor_paramsKey struct{ typeName, suffix, fnName string }

// mockConverterer_IsolationAccessor_resultsByParams contains the results for a given set of parameters for the Converterer type
type mockConverterer_IsolationAccessor_resultsByParams struct {
	anyCount  int
	anyParams uint64
	results   map[mockConverterer_IsolationAccessor_paramsKey]*mockConverterer_IsolationAccessor_results
}

// mockConverterer_IsolationAccessor_doFn defines the type of function needed when calling andDo for the Converterer type
type mockConverterer_IsolationAccessor_doFn func(typeName, suffix, fnName string)

// mockConverterer_IsolationAccessor_doReturnFn defines the type of function needed when calling doReturnResults for the Converterer type
type mockConverterer_IsolationAccessor_doReturnFn func(typeName, suffix, fnName string) (funcDecl *dst.FuncDecl)

// mockConverterer_IsolationAccessor_results holds the results of the Converterer type
type mockConverterer_IsolationAccessor_results struct {
	params  mockConverterer_IsolationAccessor_params
	results []struct {
		values     *struct{ funcDecl *dst.FuncDecl }
		sequence   uint32
		doFn       mockConverterer_IsolationAccessor_doFn
		doReturnFn mockConverterer_IsolationAccessor_doReturnFn
	}
	index    uint32
	anyTimes bool
}

// mockConverterer_IsolationAccessor_fnRecorder routes recorded function calls to the mockConverterer mock
type mockConverterer_IsolationAccessor_fnRecorder struct {
	params    mockConverterer_IsolationAccessor_params
	paramsKey mockConverterer_IsolationAccessor_paramsKey
	anyParams uint64
	sequence  bool
	results   *mockConverterer_IsolationAccessor_results
	mock      *mockConverterer
}

// mockConverterer_FuncClosure_params holds the params of the Converterer type
type mockConverterer_FuncClosure_params struct {
	typeName, pkgPath string
	fn                generator.Func
}

// mockConverterer_FuncClosure_paramsKey holds the map key params of the Converterer type
type mockConverterer_FuncClosure_paramsKey struct {
	typeName, pkgPath string
	fn                generator.Func
}

// mockConverterer_FuncClosure_resultsByParams contains the results for a given set of parameters for the Converterer type
type mockConverterer_FuncClosure_resultsByParams struct {
	anyCount  int
	anyParams uint64
	results   map[mockConverterer_FuncClosure_paramsKey]*mockConverterer_FuncClosure_results
}

// mockConverterer_FuncClosure_doFn defines the type of function needed when calling andDo for the Converterer type
type mockConverterer_FuncClosure_doFn func(typeName, pkgPath string, fn generator.Func)

// mockConverterer_FuncClosure_doReturnFn defines the type of function needed when calling doReturnResults for the Converterer type
type mockConverterer_FuncClosure_doReturnFn func(typeName, pkgPath string, fn generator.Func) (funcDecl *dst.FuncDecl)

// mockConverterer_FuncClosure_results holds the results of the Converterer type
type mockConverterer_FuncClosure_results struct {
	params  mockConverterer_FuncClosure_params
	results []struct {
		values     *struct{ funcDecl *dst.FuncDecl }
		sequence   uint32
		doFn       mockConverterer_FuncClosure_doFn
		doReturnFn mockConverterer_FuncClosure_doReturnFn
	}
	index    uint32
	anyTimes bool
}

// mockConverterer_FuncClosure_fnRecorder routes recorded function calls to the mockConverterer mock
type mockConverterer_FuncClosure_fnRecorder struct {
	params    mockConverterer_FuncClosure_params
	paramsKey mockConverterer_FuncClosure_paramsKey
	anyParams uint64
	sequence  bool
	results   *mockConverterer_FuncClosure_results
	mock      *mockConverterer
}

// mockConverterer_MockMethod_params holds the params of the Converterer type
type mockConverterer_MockMethod_params struct {
	typeName string
	fn       generator.Func
}

// mockConverterer_MockMethod_paramsKey holds the map key params of the Converterer type
type mockConverterer_MockMethod_paramsKey struct {
	typeName string
	fn       generator.Func
}

// mockConverterer_MockMethod_resultsByParams contains the results for a given set of parameters for the Converterer type
type mockConverterer_MockMethod_resultsByParams struct {
	anyCount  int
	anyParams uint64
	results   map[mockConverterer_MockMethod_paramsKey]*mockConverterer_MockMethod_results
}

// mockConverterer_MockMethod_doFn defines the type of function needed when calling andDo for the Converterer type
type mockConverterer_MockMethod_doFn func(typeName string, fn generator.Func)

// mockConverterer_MockMethod_doReturnFn defines the type of function needed when calling doReturnResults for the Converterer type
type mockConverterer_MockMethod_doReturnFn func(typeName string, fn generator.Func) (funcDecl *dst.FuncDecl)

// mockConverterer_MockMethod_results holds the results of the Converterer type
type mockConverterer_MockMethod_results struct {
	params  mockConverterer_MockMethod_params
	results []struct {
		values     *struct{ funcDecl *dst.FuncDecl }
		sequence   uint32
		doFn       mockConverterer_MockMethod_doFn
		doReturnFn mockConverterer_MockMethod_doReturnFn
	}
	index    uint32
	anyTimes bool
}

// mockConverterer_MockMethod_fnRecorder routes recorded function calls to the mockConverterer mock
type mockConverterer_MockMethod_fnRecorder struct {
	params    mockConverterer_MockMethod_params
	paramsKey mockConverterer_MockMethod_paramsKey
	anyParams uint64
	sequence  bool
	results   *mockConverterer_MockMethod_results
	mock      *mockConverterer
}

// mockConverterer_RecorderMethods_params holds the params of the Converterer type
type mockConverterer_RecorderMethods_params struct {
	typeName string
	fn       generator.Func
}

// mockConverterer_RecorderMethods_paramsKey holds the map key params of the Converterer type
type mockConverterer_RecorderMethods_paramsKey struct {
	typeName string
	fn       generator.Func
}

// mockConverterer_RecorderMethods_resultsByParams contains the results for a given set of parameters for the Converterer type
type mockConverterer_RecorderMethods_resultsByParams struct {
	anyCount  int
	anyParams uint64
	results   map[mockConverterer_RecorderMethods_paramsKey]*mockConverterer_RecorderMethods_results
}

// mockConverterer_RecorderMethods_doFn defines the type of function needed when calling andDo for the Converterer type
type mockConverterer_RecorderMethods_doFn func(typeName string, fn generator.Func)

// mockConverterer_RecorderMethods_doReturnFn defines the type of function needed when calling doReturnResults for the Converterer type
type mockConverterer_RecorderMethods_doReturnFn func(typeName string, fn generator.Func) (funcDecls []dst.Decl)

// mockConverterer_RecorderMethods_results holds the results of the Converterer type
type mockConverterer_RecorderMethods_results struct {
	params  mockConverterer_RecorderMethods_params
	results []struct {
		values     *struct{ funcDecls []dst.Decl }
		sequence   uint32
		doFn       mockConverterer_RecorderMethods_doFn
		doReturnFn mockConverterer_RecorderMethods_doReturnFn
	}
	index    uint32
	anyTimes bool
}

// mockConverterer_RecorderMethods_fnRecorder routes recorded function calls to the mockConverterer mock
type mockConverterer_RecorderMethods_fnRecorder struct {
	params    mockConverterer_RecorderMethods_params
	paramsKey mockConverterer_RecorderMethods_paramsKey
	anyParams uint64
	sequence  bool
	results   *mockConverterer_RecorderMethods_results
	mock      *mockConverterer
}

// mockConverterer_ResetMethod_params holds the params of the Converterer type
type mockConverterer_ResetMethod_params struct {
	typeSpec *dst.TypeSpec
	funcs    []generator.Func
}

// mockConverterer_ResetMethod_paramsKey holds the map key params of the Converterer type
type mockConverterer_ResetMethod_paramsKey struct {
	typeSpec *dst.TypeSpec
	funcs    hash.Hash
}

// mockConverterer_ResetMethod_resultsByParams contains the results for a given set of parameters for the Converterer type
type mockConverterer_ResetMethod_resultsByParams struct {
	anyCount  int
	anyParams uint64
	results   map[mockConverterer_ResetMethod_paramsKey]*mockConverterer_ResetMethod_results
}

// mockConverterer_ResetMethod_doFn defines the type of function needed when calling andDo for the Converterer type
type mockConverterer_ResetMethod_doFn func(typeSpec *dst.TypeSpec, funcs []generator.Func)

// mockConverterer_ResetMethod_doReturnFn defines the type of function needed when calling doReturnResults for the Converterer type
type mockConverterer_ResetMethod_doReturnFn func(typeSpec *dst.TypeSpec, funcs []generator.Func) (funcDecl *dst.FuncDecl)

// mockConverterer_ResetMethod_results holds the results of the Converterer type
type mockConverterer_ResetMethod_results struct {
	params  mockConverterer_ResetMethod_params
	results []struct {
		values     *struct{ funcDecl *dst.FuncDecl }
		sequence   uint32
		doFn       mockConverterer_ResetMethod_doFn
		doReturnFn mockConverterer_ResetMethod_doReturnFn
	}
	index    uint32
	anyTimes bool
}

// mockConverterer_ResetMethod_fnRecorder routes recorded function calls to the mockConverterer mock
type mockConverterer_ResetMethod_fnRecorder struct {
	params    mockConverterer_ResetMethod_params
	paramsKey mockConverterer_ResetMethod_paramsKey
	anyParams uint64
	sequence  bool
	results   *mockConverterer_ResetMethod_results
	mock      *mockConverterer
}

// mockConverterer_AssertMethod_params holds the params of the Converterer type
type mockConverterer_AssertMethod_params struct {
	typeSpec *dst.TypeSpec
	funcs    []generator.Func
}

// mockConverterer_AssertMethod_paramsKey holds the map key params of the Converterer type
type mockConverterer_AssertMethod_paramsKey struct {
	typeSpec *dst.TypeSpec
	funcs    hash.Hash
}

// mockConverterer_AssertMethod_resultsByParams contains the results for a given set of parameters for the Converterer type
type mockConverterer_AssertMethod_resultsByParams struct {
	anyCount  int
	anyParams uint64
	results   map[mockConverterer_AssertMethod_paramsKey]*mockConverterer_AssertMethod_results
}

// mockConverterer_AssertMethod_doFn defines the type of function needed when calling andDo for the Converterer type
type mockConverterer_AssertMethod_doFn func(typeSpec *dst.TypeSpec, funcs []generator.Func)

// mockConverterer_AssertMethod_doReturnFn defines the type of function needed when calling doReturnResults for the Converterer type
type mockConverterer_AssertMethod_doReturnFn func(typeSpec *dst.TypeSpec, funcs []generator.Func) (funcDecl *dst.FuncDecl)

// mockConverterer_AssertMethod_results holds the results of the Converterer type
type mockConverterer_AssertMethod_results struct {
	params  mockConverterer_AssertMethod_params
	results []struct {
		values     *struct{ funcDecl *dst.FuncDecl }
		sequence   uint32
		doFn       mockConverterer_AssertMethod_doFn
		doReturnFn mockConverterer_AssertMethod_doReturnFn
	}
	index    uint32
	anyTimes bool
}

// mockConverterer_AssertMethod_fnRecorder routes recorded function calls to the mockConverterer mock
type mockConverterer_AssertMethod_fnRecorder struct {
	params    mockConverterer_AssertMethod_params
	paramsKey mockConverterer_AssertMethod_paramsKey
	anyParams uint64
	sequence  bool
	results   *mockConverterer_AssertMethod_results
	mock      *mockConverterer
}

// newMockConverterer creates a new mock of the Converterer type
func newMockConverterer(scene *moq.Scene, config *moq.MockConfig) *mockConverterer {
	if config == nil {
		config = &moq.MockConfig{}
	}
	m := &mockConverterer{
		scene:  scene,
		config: *config,
	}
	scene.AddMock(m)
	return m
}

// mock returns the mock implementation of the Converterer type
func (m *mockConverterer) mock() *mockConverterer_mock {
	return &mockConverterer_mock{
		mock: m,
	}
}

func (m *mockConverterer_mock) BaseStruct(typeSpec *dst.TypeSpec, funcs []generator.Func) (structDecl *dst.GenDecl) {
	params := mockConverterer_BaseStruct_params{
		typeSpec: typeSpec,
		funcs:    funcs,
	}
	var results *mockConverterer_BaseStruct_results
	for _, resultsByParams := range m.mock.resultsByParams_BaseStruct {
		var typeSpecUsed *dst.TypeSpec
		if resultsByParams.anyParams&(1<<0) == 0 {
			typeSpecUsed = typeSpec
		}
		var funcsUsed hash.Hash
		if resultsByParams.anyParams&(1<<1) == 0 {
			funcsUsed = hash.DeepHash(funcs)
		}
		paramsKey := mockConverterer_BaseStruct_paramsKey{
			typeSpec: typeSpecUsed,
			funcs:    funcsUsed,
		}
		var ok bool
		results, ok = resultsByParams.results[paramsKey]
		if ok {
			break
		}
	}
	if results == nil {
		if m.mock.config.Expectation == moq.Strict {
			m.mock.scene.MoqT.Fatalf("Unexpected call with parameters %#v", params)
		}
		return
	}

	i := int(atomic.AddUint32(&results.index, 1)) - 1
	if i >= len(results.results) {
		if !results.anyTimes {
			if m.mock.config.Expectation == moq.Strict {
				m.mock.scene.MoqT.Fatalf("Too many calls to mock with parameters %#v", params)
			}
			return
		}
		i = len(results.results) - 1
	}

	result := results.results[i]
	if result.sequence != 0 {
		sequence := m.mock.scene.NextMockSequence()
		if (!results.anyTimes && result.sequence != sequence) || result.sequence > sequence {
			m.mock.scene.MoqT.Fatalf("Call sequence does not match %#v", params)
		}
	}

	if result.doFn != nil {
		result.doFn(typeSpec, funcs)
	}

	if result.values != nil {
		structDecl = result.values.structDecl
	}
	if result.doReturnFn != nil {
		structDecl = result.doReturnFn(typeSpec, funcs)
	}
	return
}

func (m *mockConverterer_mock) IsolationStruct(typeName, suffix string) (structDecl *dst.GenDecl) {
	params := mockConverterer_IsolationStruct_params{
		typeName: typeName,
		suffix:   suffix,
	}
	var results *mockConverterer_IsolationStruct_results
	for _, resultsByParams := range m.mock.resultsByParams_IsolationStruct {
		var typeNameUsed string
		if resultsByParams.anyParams&(1<<0) == 0 {
			typeNameUsed = typeName
		}
		var suffixUsed string
		if resultsByParams.anyParams&(1<<1) == 0 {
			suffixUsed = suffix
		}
		paramsKey := mockConverterer_IsolationStruct_paramsKey{
			typeName: typeNameUsed,
			suffix:   suffixUsed,
		}
		var ok bool
		results, ok = resultsByParams.results[paramsKey]
		if ok {
			break
		}
	}
	if results == nil {
		if m.mock.config.Expectation == moq.Strict {
			m.mock.scene.MoqT.Fatalf("Unexpected call with parameters %#v", params)
		}
		return
	}

	i := int(atomic.AddUint32(&results.index, 1)) - 1
	if i >= len(results.results) {
		if !results.anyTimes {
			if m.mock.config.Expectation == moq.Strict {
				m.mock.scene.MoqT.Fatalf("Too many calls to mock with parameters %#v", params)
			}
			return
		}
		i = len(results.results) - 1
	}

	result := results.results[i]
	if result.sequence != 0 {
		sequence := m.mock.scene.NextMockSequence()
		if (!results.anyTimes && result.sequence != sequence) || result.sequence > sequence {
			m.mock.scene.MoqT.Fatalf("Call sequence does not match %#v", params)
		}
	}

	if result.doFn != nil {
		result.doFn(typeName, suffix)
	}

	if result.values != nil {
		structDecl = result.values.structDecl
	}
	if result.doReturnFn != nil {
		structDecl = result.doReturnFn(typeName, suffix)
	}
	return
}

func (m *mockConverterer_mock) MethodStructs(typeSpec *dst.TypeSpec, fn generator.Func) (structDecls []dst.Decl) {
	params := mockConverterer_MethodStructs_params{
		typeSpec: typeSpec,
		fn:       fn,
	}
	var results *mockConverterer_MethodStructs_results
	for _, resultsByParams := range m.mock.resultsByParams_MethodStructs {
		var typeSpecUsed *dst.TypeSpec
		if resultsByParams.anyParams&(1<<0) == 0 {
			typeSpecUsed = typeSpec
		}
		var fnUsed generator.Func
		if resultsByParams.anyParams&(1<<1) == 0 {
			fnUsed = fn
		}
		paramsKey := mockConverterer_MethodStructs_paramsKey{
			typeSpec: typeSpecUsed,
			fn:       fnUsed,
		}
		var ok bool
		results, ok = resultsByParams.results[paramsKey]
		if ok {
			break
		}
	}
	if results == nil {
		if m.mock.config.Expectation == moq.Strict {
			m.mock.scene.MoqT.Fatalf("Unexpected call with parameters %#v", params)
		}
		return
	}

	i := int(atomic.AddUint32(&results.index, 1)) - 1
	if i >= len(results.results) {
		if !results.anyTimes {
			if m.mock.config.Expectation == moq.Strict {
				m.mock.scene.MoqT.Fatalf("Too many calls to mock with parameters %#v", params)
			}
			return
		}
		i = len(results.results) - 1
	}

	result := results.results[i]
	if result.sequence != 0 {
		sequence := m.mock.scene.NextMockSequence()
		if (!results.anyTimes && result.sequence != sequence) || result.sequence > sequence {
			m.mock.scene.MoqT.Fatalf("Call sequence does not match %#v", params)
		}
	}

	if result.doFn != nil {
		result.doFn(typeSpec, fn)
	}

	if result.values != nil {
		structDecls = result.values.structDecls
	}
	if result.doReturnFn != nil {
		structDecls = result.doReturnFn(typeSpec, fn)
	}
	return
}

func (m *mockConverterer_mock) NewFunc(typeSpec *dst.TypeSpec) (funcDecl *dst.FuncDecl) {
	params := mockConverterer_NewFunc_params{
		typeSpec: typeSpec,
	}
	var results *mockConverterer_NewFunc_results
	for _, resultsByParams := range m.mock.resultsByParams_NewFunc {
		var typeSpecUsed *dst.TypeSpec
		if resultsByParams.anyParams&(1<<0) == 0 {
			typeSpecUsed = typeSpec
		}
		paramsKey := mockConverterer_NewFunc_paramsKey{
			typeSpec: typeSpecUsed,
		}
		var ok bool
		results, ok = resultsByParams.results[paramsKey]
		if ok {
			break
		}
	}
	if results == nil {
		if m.mock.config.Expectation == moq.Strict {
			m.mock.scene.MoqT.Fatalf("Unexpected call with parameters %#v", params)
		}
		return
	}

	i := int(atomic.AddUint32(&results.index, 1)) - 1
	if i >= len(results.results) {
		if !results.anyTimes {
			if m.mock.config.Expectation == moq.Strict {
				m.mock.scene.MoqT.Fatalf("Too many calls to mock with parameters %#v", params)
			}
			return
		}
		i = len(results.results) - 1
	}

	result := results.results[i]
	if result.sequence != 0 {
		sequence := m.mock.scene.NextMockSequence()
		if (!results.anyTimes && result.sequence != sequence) || result.sequence > sequence {
			m.mock.scene.MoqT.Fatalf("Call sequence does not match %#v", params)
		}
	}

	if result.doFn != nil {
		result.doFn(typeSpec)
	}

	if result.values != nil {
		funcDecl = result.values.funcDecl
	}
	if result.doReturnFn != nil {
		funcDecl = result.doReturnFn(typeSpec)
	}
	return
}

func (m *mockConverterer_mock) IsolationAccessor(typeName, suffix, fnName string) (funcDecl *dst.FuncDecl) {
	params := mockConverterer_IsolationAccessor_params{
		typeName: typeName,
		suffix:   suffix,
		fnName:   fnName,
	}
	var results *mockConverterer_IsolationAccessor_results
	for _, resultsByParams := range m.mock.resultsByParams_IsolationAccessor {
		var typeNameUsed string
		if resultsByParams.anyParams&(1<<0) == 0 {
			typeNameUsed = typeName
		}
		var suffixUsed string
		if resultsByParams.anyParams&(1<<1) == 0 {
			suffixUsed = suffix
		}
		var fnNameUsed string
		if resultsByParams.anyParams&(1<<2) == 0 {
			fnNameUsed = fnName
		}
		paramsKey := mockConverterer_IsolationAccessor_paramsKey{
			typeName: typeNameUsed,
			suffix:   suffixUsed,
			fnName:   fnNameUsed,
		}
		var ok bool
		results, ok = resultsByParams.results[paramsKey]
		if ok {
			break
		}
	}
	if results == nil {
		if m.mock.config.Expectation == moq.Strict {
			m.mock.scene.MoqT.Fatalf("Unexpected call with parameters %#v", params)
		}
		return
	}

	i := int(atomic.AddUint32(&results.index, 1)) - 1
	if i >= len(results.results) {
		if !results.anyTimes {
			if m.mock.config.Expectation == moq.Strict {
				m.mock.scene.MoqT.Fatalf("Too many calls to mock with parameters %#v", params)
			}
			return
		}
		i = len(results.results) - 1
	}

	result := results.results[i]
	if result.sequence != 0 {
		sequence := m.mock.scene.NextMockSequence()
		if (!results.anyTimes && result.sequence != sequence) || result.sequence > sequence {
			m.mock.scene.MoqT.Fatalf("Call sequence does not match %#v", params)
		}
	}

	if result.doFn != nil {
		result.doFn(typeName, suffix, fnName)
	}

	if result.values != nil {
		funcDecl = result.values.funcDecl
	}
	if result.doReturnFn != nil {
		funcDecl = result.doReturnFn(typeName, suffix, fnName)
	}
	return
}

func (m *mockConverterer_mock) FuncClosure(typeName, pkgPath string, fn generator.Func) (funcDecl *dst.FuncDecl) {
	params := mockConverterer_FuncClosure_params{
		typeName: typeName,
		pkgPath:  pkgPath,
		fn:       fn,
	}
	var results *mockConverterer_FuncClosure_results
	for _, resultsByParams := range m.mock.resultsByParams_FuncClosure {
		var typeNameUsed string
		if resultsByParams.anyParams&(1<<0) == 0 {
			typeNameUsed = typeName
		}
		var pkgPathUsed string
		if resultsByParams.anyParams&(1<<1) == 0 {
			pkgPathUsed = pkgPath
		}
		var fnUsed generator.Func
		if resultsByParams.anyParams&(1<<2) == 0 {
			fnUsed = fn
		}
		paramsKey := mockConverterer_FuncClosure_paramsKey{
			typeName: typeNameUsed,
			pkgPath:  pkgPathUsed,
			fn:       fnUsed,
		}
		var ok bool
		results, ok = resultsByParams.results[paramsKey]
		if ok {
			break
		}
	}
	if results == nil {
		if m.mock.config.Expectation == moq.Strict {
			m.mock.scene.MoqT.Fatalf("Unexpected call with parameters %#v", params)
		}
		return
	}

	i := int(atomic.AddUint32(&results.index, 1)) - 1
	if i >= len(results.results) {
		if !results.anyTimes {
			if m.mock.config.Expectation == moq.Strict {
				m.mock.scene.MoqT.Fatalf("Too many calls to mock with parameters %#v", params)
			}
			return
		}
		i = len(results.results) - 1
	}

	result := results.results[i]
	if result.sequence != 0 {
		sequence := m.mock.scene.NextMockSequence()
		if (!results.anyTimes && result.sequence != sequence) || result.sequence > sequence {
			m.mock.scene.MoqT.Fatalf("Call sequence does not match %#v", params)
		}
	}

	if result.doFn != nil {
		result.doFn(typeName, pkgPath, fn)
	}

	if result.values != nil {
		funcDecl = result.values.funcDecl
	}
	if result.doReturnFn != nil {
		funcDecl = result.doReturnFn(typeName, pkgPath, fn)
	}
	return
}

func (m *mockConverterer_mock) MockMethod(typeName string, fn generator.Func) (funcDecl *dst.FuncDecl) {
	params := mockConverterer_MockMethod_params{
		typeName: typeName,
		fn:       fn,
	}
	var results *mockConverterer_MockMethod_results
	for _, resultsByParams := range m.mock.resultsByParams_MockMethod {
		var typeNameUsed string
		if resultsByParams.anyParams&(1<<0) == 0 {
			typeNameUsed = typeName
		}
		var fnUsed generator.Func
		if resultsByParams.anyParams&(1<<1) == 0 {
			fnUsed = fn
		}
		paramsKey := mockConverterer_MockMethod_paramsKey{
			typeName: typeNameUsed,
			fn:       fnUsed,
		}
		var ok bool
		results, ok = resultsByParams.results[paramsKey]
		if ok {
			break
		}
	}
	if results == nil {
		if m.mock.config.Expectation == moq.Strict {
			m.mock.scene.MoqT.Fatalf("Unexpected call with parameters %#v", params)
		}
		return
	}

	i := int(atomic.AddUint32(&results.index, 1)) - 1
	if i >= len(results.results) {
		if !results.anyTimes {
			if m.mock.config.Expectation == moq.Strict {
				m.mock.scene.MoqT.Fatalf("Too many calls to mock with parameters %#v", params)
			}
			return
		}
		i = len(results.results) - 1
	}

	result := results.results[i]
	if result.sequence != 0 {
		sequence := m.mock.scene.NextMockSequence()
		if (!results.anyTimes && result.sequence != sequence) || result.sequence > sequence {
			m.mock.scene.MoqT.Fatalf("Call sequence does not match %#v", params)
		}
	}

	if result.doFn != nil {
		result.doFn(typeName, fn)
	}

	if result.values != nil {
		funcDecl = result.values.funcDecl
	}
	if result.doReturnFn != nil {
		funcDecl = result.doReturnFn(typeName, fn)
	}
	return
}

func (m *mockConverterer_mock) RecorderMethods(typeName string, fn generator.Func) (funcDecls []dst.Decl) {
	params := mockConverterer_RecorderMethods_params{
		typeName: typeName,
		fn:       fn,
	}
	var results *mockConverterer_RecorderMethods_results
	for _, resultsByParams := range m.mock.resultsByParams_RecorderMethods {
		var typeNameUsed string
		if resultsByParams.anyParams&(1<<0) == 0 {
			typeNameUsed = typeName
		}
		var fnUsed generator.Func
		if resultsByParams.anyParams&(1<<1) == 0 {
			fnUsed = fn
		}
		paramsKey := mockConverterer_RecorderMethods_paramsKey{
			typeName: typeNameUsed,
			fn:       fnUsed,
		}
		var ok bool
		results, ok = resultsByParams.results[paramsKey]
		if ok {
			break
		}
	}
	if results == nil {
		if m.mock.config.Expectation == moq.Strict {
			m.mock.scene.MoqT.Fatalf("Unexpected call with parameters %#v", params)
		}
		return
	}

	i := int(atomic.AddUint32(&results.index, 1)) - 1
	if i >= len(results.results) {
		if !results.anyTimes {
			if m.mock.config.Expectation == moq.Strict {
				m.mock.scene.MoqT.Fatalf("Too many calls to mock with parameters %#v", params)
			}
			return
		}
		i = len(results.results) - 1
	}

	result := results.results[i]
	if result.sequence != 0 {
		sequence := m.mock.scene.NextMockSequence()
		if (!results.anyTimes && result.sequence != sequence) || result.sequence > sequence {
			m.mock.scene.MoqT.Fatalf("Call sequence does not match %#v", params)
		}
	}

	if result.doFn != nil {
		result.doFn(typeName, fn)
	}

	if result.values != nil {
		funcDecls = result.values.funcDecls
	}
	if result.doReturnFn != nil {
		funcDecls = result.doReturnFn(typeName, fn)
	}
	return
}

func (m *mockConverterer_mock) ResetMethod(typeSpec *dst.TypeSpec, funcs []generator.Func) (funcDecl *dst.FuncDecl) {
	params := mockConverterer_ResetMethod_params{
		typeSpec: typeSpec,
		funcs:    funcs,
	}
	var results *mockConverterer_ResetMethod_results
	for _, resultsByParams := range m.mock.resultsByParams_ResetMethod {
		var typeSpecUsed *dst.TypeSpec
		if resultsByParams.anyParams&(1<<0) == 0 {
			typeSpecUsed = typeSpec
		}
		var funcsUsed hash.Hash
		if resultsByParams.anyParams&(1<<1) == 0 {
			funcsUsed = hash.DeepHash(funcs)
		}
		paramsKey := mockConverterer_ResetMethod_paramsKey{
			typeSpec: typeSpecUsed,
			funcs:    funcsUsed,
		}
		var ok bool
		results, ok = resultsByParams.results[paramsKey]
		if ok {
			break
		}
	}
	if results == nil {
		if m.mock.config.Expectation == moq.Strict {
			m.mock.scene.MoqT.Fatalf("Unexpected call with parameters %#v", params)
		}
		return
	}

	i := int(atomic.AddUint32(&results.index, 1)) - 1
	if i >= len(results.results) {
		if !results.anyTimes {
			if m.mock.config.Expectation == moq.Strict {
				m.mock.scene.MoqT.Fatalf("Too many calls to mock with parameters %#v", params)
			}
			return
		}
		i = len(results.results) - 1
	}

	result := results.results[i]
	if result.sequence != 0 {
		sequence := m.mock.scene.NextMockSequence()
		if (!results.anyTimes && result.sequence != sequence) || result.sequence > sequence {
			m.mock.scene.MoqT.Fatalf("Call sequence does not match %#v", params)
		}
	}

	if result.doFn != nil {
		result.doFn(typeSpec, funcs)
	}

	if result.values != nil {
		funcDecl = result.values.funcDecl
	}
	if result.doReturnFn != nil {
		funcDecl = result.doReturnFn(typeSpec, funcs)
	}
	return
}

func (m *mockConverterer_mock) AssertMethod(typeSpec *dst.TypeSpec, funcs []generator.Func) (funcDecl *dst.FuncDecl) {
	params := mockConverterer_AssertMethod_params{
		typeSpec: typeSpec,
		funcs:    funcs,
	}
	var results *mockConverterer_AssertMethod_results
	for _, resultsByParams := range m.mock.resultsByParams_AssertMethod {
		var typeSpecUsed *dst.TypeSpec
		if resultsByParams.anyParams&(1<<0) == 0 {
			typeSpecUsed = typeSpec
		}
		var funcsUsed hash.Hash
		if resultsByParams.anyParams&(1<<1) == 0 {
			funcsUsed = hash.DeepHash(funcs)
		}
		paramsKey := mockConverterer_AssertMethod_paramsKey{
			typeSpec: typeSpecUsed,
			funcs:    funcsUsed,
		}
		var ok bool
		results, ok = resultsByParams.results[paramsKey]
		if ok {
			break
		}
	}
	if results == nil {
		if m.mock.config.Expectation == moq.Strict {
			m.mock.scene.MoqT.Fatalf("Unexpected call with parameters %#v", params)
		}
		return
	}

	i := int(atomic.AddUint32(&results.index, 1)) - 1
	if i >= len(results.results) {
		if !results.anyTimes {
			if m.mock.config.Expectation == moq.Strict {
				m.mock.scene.MoqT.Fatalf("Too many calls to mock with parameters %#v", params)
			}
			return
		}
		i = len(results.results) - 1
	}

	result := results.results[i]
	if result.sequence != 0 {
		sequence := m.mock.scene.NextMockSequence()
		if (!results.anyTimes && result.sequence != sequence) || result.sequence > sequence {
			m.mock.scene.MoqT.Fatalf("Call sequence does not match %#v", params)
		}
	}

	if result.doFn != nil {
		result.doFn(typeSpec, funcs)
	}

	if result.values != nil {
		funcDecl = result.values.funcDecl
	}
	if result.doReturnFn != nil {
		funcDecl = result.doReturnFn(typeSpec, funcs)
	}
	return
}

// onCall returns the recorder implementation of the Converterer type
func (m *mockConverterer) onCall() *mockConverterer_recorder {
	return &mockConverterer_recorder{
		mock: m,
	}
}

func (m *mockConverterer_recorder) BaseStruct(typeSpec *dst.TypeSpec, funcs []generator.Func) *mockConverterer_BaseStruct_fnRecorder {
	return &mockConverterer_BaseStruct_fnRecorder{
		params: mockConverterer_BaseStruct_params{
			typeSpec: typeSpec,
			funcs:    funcs,
		},
		paramsKey: mockConverterer_BaseStruct_paramsKey{
			typeSpec: typeSpec,
			funcs:    hash.DeepHash(funcs),
		},
		sequence: m.mock.config.Sequence == moq.SeqDefaultOn,
		mock:     m.mock,
	}
}

func (r *mockConverterer_BaseStruct_fnRecorder) anyTypeSpec() *mockConverterer_BaseStruct_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("Any functions must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.anyParams |= 1 << 0
	return r
}

func (r *mockConverterer_BaseStruct_fnRecorder) anyFuncs() *mockConverterer_BaseStruct_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("Any functions must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.anyParams |= 1 << 1
	return r
}

func (r *mockConverterer_BaseStruct_fnRecorder) seq() *mockConverterer_BaseStruct_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("seq must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.sequence = true
	return r
}

func (r *mockConverterer_BaseStruct_fnRecorder) noSeq() *mockConverterer_BaseStruct_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("noSeq must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.sequence = false
	return r
}

func (r *mockConverterer_BaseStruct_fnRecorder) returnResults(structDecl *dst.GenDecl) *mockConverterer_BaseStruct_fnRecorder {
	r.findResults()

	var sequence uint32
	if r.sequence {
		sequence = r.mock.scene.NextRecorderSequence()
	}

	r.results.results = append(r.results.results, struct {
		values     *struct{ structDecl *dst.GenDecl }
		sequence   uint32
		doFn       mockConverterer_BaseStruct_doFn
		doReturnFn mockConverterer_BaseStruct_doReturnFn
	}{
		values: &struct{ structDecl *dst.GenDecl }{
			structDecl: structDecl,
		},
		sequence: sequence,
	})
	return r
}

func (r *mockConverterer_BaseStruct_fnRecorder) andDo(fn mockConverterer_BaseStruct_doFn) *mockConverterer_BaseStruct_fnRecorder {
	if r.results == nil {
		r.mock.scene.MoqT.Fatalf("returnResults must be called before calling andDo")
		return nil
	}
	last := &r.results.results[len(r.results.results)-1]
	last.doFn = fn
	return r
}

func (r *mockConverterer_BaseStruct_fnRecorder) doReturnResults(fn mockConverterer_BaseStruct_doReturnFn) *mockConverterer_BaseStruct_fnRecorder {
	r.findResults()

	var sequence uint32
	if r.sequence {
		sequence = r.mock.scene.NextRecorderSequence()
	}

	r.results.results = append(r.results.results, struct {
		values     *struct{ structDecl *dst.GenDecl }
		sequence   uint32
		doFn       mockConverterer_BaseStruct_doFn
		doReturnFn mockConverterer_BaseStruct_doReturnFn
	}{sequence: sequence, doReturnFn: fn})
	return r
}

func (r *mockConverterer_BaseStruct_fnRecorder) findResults() {
	if r.results == nil {
		anyCount := bits.OnesCount64(r.anyParams)
		insertAt := -1
		var results *mockConverterer_BaseStruct_resultsByParams
		for n, res := range r.mock.resultsByParams_BaseStruct {
			if res.anyParams == r.anyParams {
				results = &res
				break
			}
			if res.anyCount > anyCount {
				insertAt = n
			}
		}
		if results == nil {
			results = &mockConverterer_BaseStruct_resultsByParams{
				anyCount:  anyCount,
				anyParams: r.anyParams,
				results:   map[mockConverterer_BaseStruct_paramsKey]*mockConverterer_BaseStruct_results{},
			}
			r.mock.resultsByParams_BaseStruct = append(r.mock.resultsByParams_BaseStruct, *results)
			if insertAt != -1 && insertAt+1 < len(r.mock.resultsByParams_BaseStruct) {
				copy(r.mock.resultsByParams_BaseStruct[insertAt+1:], r.mock.resultsByParams_BaseStruct[insertAt:0])
				r.mock.resultsByParams_BaseStruct[insertAt] = *results
			}
		}

		var typeSpecUsed *dst.TypeSpec
		if r.anyParams&(1<<0) == 0 {
			typeSpecUsed = r.paramsKey.typeSpec
		}
		var funcsUsed hash.Hash
		if r.anyParams&(1<<1) == 0 {
			funcsUsed = r.paramsKey.funcs
		}
		paramsKey := mockConverterer_BaseStruct_paramsKey{
			typeSpec: typeSpecUsed,
			funcs:    funcsUsed,
		}

		var ok bool
		r.results, ok = results.results[paramsKey]
		if !ok {
			r.results = &mockConverterer_BaseStruct_results{
				params:   r.params,
				results:  nil,
				index:    0,
				anyTimes: false,
			}
			results.results[paramsKey] = r.results
		}
	}
}

func (r *mockConverterer_BaseStruct_fnRecorder) times(count int) *mockConverterer_BaseStruct_fnRecorder {
	if r.results == nil {
		r.mock.scene.MoqT.Fatalf("returnResults or doReturnResults must be called before calling times")
		return nil
	}
	last := r.results.results[len(r.results.results)-1]
	for n := 0; n < count-1; n++ {
		if last.sequence != 0 {
			last = struct {
				values     *struct{ structDecl *dst.GenDecl }
				sequence   uint32
				doFn       mockConverterer_BaseStruct_doFn
				doReturnFn mockConverterer_BaseStruct_doReturnFn
			}{
				values: &struct{ structDecl *dst.GenDecl }{
					structDecl: last.values.structDecl,
				},
				sequence: r.mock.scene.NextRecorderSequence(),
			}
		}
		r.results.results = append(r.results.results, last)
	}
	return r
}

func (r *mockConverterer_BaseStruct_fnRecorder) anyTimes() {
	if r.results == nil {
		r.mock.scene.MoqT.Fatalf("returnResults or doReturnResults must be called before calling anyTimes")
		return
	}
	r.results.anyTimes = true
}

func (m *mockConverterer_recorder) IsolationStruct(typeName, suffix string) *mockConverterer_IsolationStruct_fnRecorder {
	return &mockConverterer_IsolationStruct_fnRecorder{
		params: mockConverterer_IsolationStruct_params{
			typeName: typeName,
			suffix:   suffix,
		},
		paramsKey: mockConverterer_IsolationStruct_paramsKey{
			typeName: typeName,
			suffix:   suffix,
		},
		sequence: m.mock.config.Sequence == moq.SeqDefaultOn,
		mock:     m.mock,
	}
}

func (r *mockConverterer_IsolationStruct_fnRecorder) anyTypeName() *mockConverterer_IsolationStruct_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("Any functions must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.anyParams |= 1 << 0
	return r
}

func (r *mockConverterer_IsolationStruct_fnRecorder) anySuffix() *mockConverterer_IsolationStruct_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("Any functions must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.anyParams |= 1 << 1
	return r
}

func (r *mockConverterer_IsolationStruct_fnRecorder) seq() *mockConverterer_IsolationStruct_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("seq must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.sequence = true
	return r
}

func (r *mockConverterer_IsolationStruct_fnRecorder) noSeq() *mockConverterer_IsolationStruct_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("noSeq must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.sequence = false
	return r
}

func (r *mockConverterer_IsolationStruct_fnRecorder) returnResults(structDecl *dst.GenDecl) *mockConverterer_IsolationStruct_fnRecorder {
	r.findResults()

	var sequence uint32
	if r.sequence {
		sequence = r.mock.scene.NextRecorderSequence()
	}

	r.results.results = append(r.results.results, struct {
		values     *struct{ structDecl *dst.GenDecl }
		sequence   uint32
		doFn       mockConverterer_IsolationStruct_doFn
		doReturnFn mockConverterer_IsolationStruct_doReturnFn
	}{
		values: &struct{ structDecl *dst.GenDecl }{
			structDecl: structDecl,
		},
		sequence: sequence,
	})
	return r
}

func (r *mockConverterer_IsolationStruct_fnRecorder) andDo(fn mockConverterer_IsolationStruct_doFn) *mockConverterer_IsolationStruct_fnRecorder {
	if r.results == nil {
		r.mock.scene.MoqT.Fatalf("returnResults must be called before calling andDo")
		return nil
	}
	last := &r.results.results[len(r.results.results)-1]
	last.doFn = fn
	return r
}

func (r *mockConverterer_IsolationStruct_fnRecorder) doReturnResults(fn mockConverterer_IsolationStruct_doReturnFn) *mockConverterer_IsolationStruct_fnRecorder {
	r.findResults()

	var sequence uint32
	if r.sequence {
		sequence = r.mock.scene.NextRecorderSequence()
	}

	r.results.results = append(r.results.results, struct {
		values     *struct{ structDecl *dst.GenDecl }
		sequence   uint32
		doFn       mockConverterer_IsolationStruct_doFn
		doReturnFn mockConverterer_IsolationStruct_doReturnFn
	}{sequence: sequence, doReturnFn: fn})
	return r
}

func (r *mockConverterer_IsolationStruct_fnRecorder) findResults() {
	if r.results == nil {
		anyCount := bits.OnesCount64(r.anyParams)
		insertAt := -1
		var results *mockConverterer_IsolationStruct_resultsByParams
		for n, res := range r.mock.resultsByParams_IsolationStruct {
			if res.anyParams == r.anyParams {
				results = &res
				break
			}
			if res.anyCount > anyCount {
				insertAt = n
			}
		}
		if results == nil {
			results = &mockConverterer_IsolationStruct_resultsByParams{
				anyCount:  anyCount,
				anyParams: r.anyParams,
				results:   map[mockConverterer_IsolationStruct_paramsKey]*mockConverterer_IsolationStruct_results{},
			}
			r.mock.resultsByParams_IsolationStruct = append(r.mock.resultsByParams_IsolationStruct, *results)
			if insertAt != -1 && insertAt+1 < len(r.mock.resultsByParams_IsolationStruct) {
				copy(r.mock.resultsByParams_IsolationStruct[insertAt+1:], r.mock.resultsByParams_IsolationStruct[insertAt:0])
				r.mock.resultsByParams_IsolationStruct[insertAt] = *results
			}
		}

		var typeNameUsed string
		if r.anyParams&(1<<0) == 0 {
			typeNameUsed = r.paramsKey.typeName
		}
		var suffixUsed string
		if r.anyParams&(1<<1) == 0 {
			suffixUsed = r.paramsKey.suffix
		}
		paramsKey := mockConverterer_IsolationStruct_paramsKey{
			typeName: typeNameUsed,
			suffix:   suffixUsed,
		}

		var ok bool
		r.results, ok = results.results[paramsKey]
		if !ok {
			r.results = &mockConverterer_IsolationStruct_results{
				params:   r.params,
				results:  nil,
				index:    0,
				anyTimes: false,
			}
			results.results[paramsKey] = r.results
		}
	}
}

func (r *mockConverterer_IsolationStruct_fnRecorder) times(count int) *mockConverterer_IsolationStruct_fnRecorder {
	if r.results == nil {
		r.mock.scene.MoqT.Fatalf("returnResults or doReturnResults must be called before calling times")
		return nil
	}
	last := r.results.results[len(r.results.results)-1]
	for n := 0; n < count-1; n++ {
		if last.sequence != 0 {
			last = struct {
				values     *struct{ structDecl *dst.GenDecl }
				sequence   uint32
				doFn       mockConverterer_IsolationStruct_doFn
				doReturnFn mockConverterer_IsolationStruct_doReturnFn
			}{
				values: &struct{ structDecl *dst.GenDecl }{
					structDecl: last.values.structDecl,
				},
				sequence: r.mock.scene.NextRecorderSequence(),
			}
		}
		r.results.results = append(r.results.results, last)
	}
	return r
}

func (r *mockConverterer_IsolationStruct_fnRecorder) anyTimes() {
	if r.results == nil {
		r.mock.scene.MoqT.Fatalf("returnResults or doReturnResults must be called before calling anyTimes")
		return
	}
	r.results.anyTimes = true
}

func (m *mockConverterer_recorder) MethodStructs(typeSpec *dst.TypeSpec, fn generator.Func) *mockConverterer_MethodStructs_fnRecorder {
	return &mockConverterer_MethodStructs_fnRecorder{
		params: mockConverterer_MethodStructs_params{
			typeSpec: typeSpec,
			fn:       fn,
		},
		paramsKey: mockConverterer_MethodStructs_paramsKey{
			typeSpec: typeSpec,
			fn:       fn,
		},
		sequence: m.mock.config.Sequence == moq.SeqDefaultOn,
		mock:     m.mock,
	}
}

func (r *mockConverterer_MethodStructs_fnRecorder) anyTypeSpec() *mockConverterer_MethodStructs_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("Any functions must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.anyParams |= 1 << 0
	return r
}

func (r *mockConverterer_MethodStructs_fnRecorder) anyFn() *mockConverterer_MethodStructs_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("Any functions must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.anyParams |= 1 << 1
	return r
}

func (r *mockConverterer_MethodStructs_fnRecorder) seq() *mockConverterer_MethodStructs_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("seq must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.sequence = true
	return r
}

func (r *mockConverterer_MethodStructs_fnRecorder) noSeq() *mockConverterer_MethodStructs_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("noSeq must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.sequence = false
	return r
}

func (r *mockConverterer_MethodStructs_fnRecorder) returnResults(structDecls []dst.Decl) *mockConverterer_MethodStructs_fnRecorder {
	r.findResults()

	var sequence uint32
	if r.sequence {
		sequence = r.mock.scene.NextRecorderSequence()
	}

	r.results.results = append(r.results.results, struct {
		values     *struct{ structDecls []dst.Decl }
		sequence   uint32
		doFn       mockConverterer_MethodStructs_doFn
		doReturnFn mockConverterer_MethodStructs_doReturnFn
	}{
		values: &struct{ structDecls []dst.Decl }{
			structDecls: structDecls,
		},
		sequence: sequence,
	})
	return r
}

func (r *mockConverterer_MethodStructs_fnRecorder) andDo(fn mockConverterer_MethodStructs_doFn) *mockConverterer_MethodStructs_fnRecorder {
	if r.results == nil {
		r.mock.scene.MoqT.Fatalf("returnResults must be called before calling andDo")
		return nil
	}
	last := &r.results.results[len(r.results.results)-1]
	last.doFn = fn
	return r
}

func (r *mockConverterer_MethodStructs_fnRecorder) doReturnResults(fn mockConverterer_MethodStructs_doReturnFn) *mockConverterer_MethodStructs_fnRecorder {
	r.findResults()

	var sequence uint32
	if r.sequence {
		sequence = r.mock.scene.NextRecorderSequence()
	}

	r.results.results = append(r.results.results, struct {
		values     *struct{ structDecls []dst.Decl }
		sequence   uint32
		doFn       mockConverterer_MethodStructs_doFn
		doReturnFn mockConverterer_MethodStructs_doReturnFn
	}{sequence: sequence, doReturnFn: fn})
	return r
}

func (r *mockConverterer_MethodStructs_fnRecorder) findResults() {
	if r.results == nil {
		anyCount := bits.OnesCount64(r.anyParams)
		insertAt := -1
		var results *mockConverterer_MethodStructs_resultsByParams
		for n, res := range r.mock.resultsByParams_MethodStructs {
			if res.anyParams == r.anyParams {
				results = &res
				break
			}
			if res.anyCount > anyCount {
				insertAt = n
			}
		}
		if results == nil {
			results = &mockConverterer_MethodStructs_resultsByParams{
				anyCount:  anyCount,
				anyParams: r.anyParams,
				results:   map[mockConverterer_MethodStructs_paramsKey]*mockConverterer_MethodStructs_results{},
			}
			r.mock.resultsByParams_MethodStructs = append(r.mock.resultsByParams_MethodStructs, *results)
			if insertAt != -1 && insertAt+1 < len(r.mock.resultsByParams_MethodStructs) {
				copy(r.mock.resultsByParams_MethodStructs[insertAt+1:], r.mock.resultsByParams_MethodStructs[insertAt:0])
				r.mock.resultsByParams_MethodStructs[insertAt] = *results
			}
		}

		var typeSpecUsed *dst.TypeSpec
		if r.anyParams&(1<<0) == 0 {
			typeSpecUsed = r.paramsKey.typeSpec
		}
		var fnUsed generator.Func
		if r.anyParams&(1<<1) == 0 {
			fnUsed = r.paramsKey.fn
		}
		paramsKey := mockConverterer_MethodStructs_paramsKey{
			typeSpec: typeSpecUsed,
			fn:       fnUsed,
		}

		var ok bool
		r.results, ok = results.results[paramsKey]
		if !ok {
			r.results = &mockConverterer_MethodStructs_results{
				params:   r.params,
				results:  nil,
				index:    0,
				anyTimes: false,
			}
			results.results[paramsKey] = r.results
		}
	}
}

func (r *mockConverterer_MethodStructs_fnRecorder) times(count int) *mockConverterer_MethodStructs_fnRecorder {
	if r.results == nil {
		r.mock.scene.MoqT.Fatalf("returnResults or doReturnResults must be called before calling times")
		return nil
	}
	last := r.results.results[len(r.results.results)-1]
	for n := 0; n < count-1; n++ {
		if last.sequence != 0 {
			last = struct {
				values     *struct{ structDecls []dst.Decl }
				sequence   uint32
				doFn       mockConverterer_MethodStructs_doFn
				doReturnFn mockConverterer_MethodStructs_doReturnFn
			}{
				values: &struct{ structDecls []dst.Decl }{
					structDecls: last.values.structDecls,
				},
				sequence: r.mock.scene.NextRecorderSequence(),
			}
		}
		r.results.results = append(r.results.results, last)
	}
	return r
}

func (r *mockConverterer_MethodStructs_fnRecorder) anyTimes() {
	if r.results == nil {
		r.mock.scene.MoqT.Fatalf("returnResults or doReturnResults must be called before calling anyTimes")
		return
	}
	r.results.anyTimes = true
}

func (m *mockConverterer_recorder) NewFunc(typeSpec *dst.TypeSpec) *mockConverterer_NewFunc_fnRecorder {
	return &mockConverterer_NewFunc_fnRecorder{
		params: mockConverterer_NewFunc_params{
			typeSpec: typeSpec,
		},
		paramsKey: mockConverterer_NewFunc_paramsKey{
			typeSpec: typeSpec,
		},
		sequence: m.mock.config.Sequence == moq.SeqDefaultOn,
		mock:     m.mock,
	}
}

func (r *mockConverterer_NewFunc_fnRecorder) anyTypeSpec() *mockConverterer_NewFunc_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("Any functions must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.anyParams |= 1 << 0
	return r
}

func (r *mockConverterer_NewFunc_fnRecorder) seq() *mockConverterer_NewFunc_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("seq must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.sequence = true
	return r
}

func (r *mockConverterer_NewFunc_fnRecorder) noSeq() *mockConverterer_NewFunc_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("noSeq must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.sequence = false
	return r
}

func (r *mockConverterer_NewFunc_fnRecorder) returnResults(funcDecl *dst.FuncDecl) *mockConverterer_NewFunc_fnRecorder {
	r.findResults()

	var sequence uint32
	if r.sequence {
		sequence = r.mock.scene.NextRecorderSequence()
	}

	r.results.results = append(r.results.results, struct {
		values     *struct{ funcDecl *dst.FuncDecl }
		sequence   uint32
		doFn       mockConverterer_NewFunc_doFn
		doReturnFn mockConverterer_NewFunc_doReturnFn
	}{
		values: &struct{ funcDecl *dst.FuncDecl }{
			funcDecl: funcDecl,
		},
		sequence: sequence,
	})
	return r
}

func (r *mockConverterer_NewFunc_fnRecorder) andDo(fn mockConverterer_NewFunc_doFn) *mockConverterer_NewFunc_fnRecorder {
	if r.results == nil {
		r.mock.scene.MoqT.Fatalf("returnResults must be called before calling andDo")
		return nil
	}
	last := &r.results.results[len(r.results.results)-1]
	last.doFn = fn
	return r
}

func (r *mockConverterer_NewFunc_fnRecorder) doReturnResults(fn mockConverterer_NewFunc_doReturnFn) *mockConverterer_NewFunc_fnRecorder {
	r.findResults()

	var sequence uint32
	if r.sequence {
		sequence = r.mock.scene.NextRecorderSequence()
	}

	r.results.results = append(r.results.results, struct {
		values     *struct{ funcDecl *dst.FuncDecl }
		sequence   uint32
		doFn       mockConverterer_NewFunc_doFn
		doReturnFn mockConverterer_NewFunc_doReturnFn
	}{sequence: sequence, doReturnFn: fn})
	return r
}

func (r *mockConverterer_NewFunc_fnRecorder) findResults() {
	if r.results == nil {
		anyCount := bits.OnesCount64(r.anyParams)
		insertAt := -1
		var results *mockConverterer_NewFunc_resultsByParams
		for n, res := range r.mock.resultsByParams_NewFunc {
			if res.anyParams == r.anyParams {
				results = &res
				break
			}
			if res.anyCount > anyCount {
				insertAt = n
			}
		}
		if results == nil {
			results = &mockConverterer_NewFunc_resultsByParams{
				anyCount:  anyCount,
				anyParams: r.anyParams,
				results:   map[mockConverterer_NewFunc_paramsKey]*mockConverterer_NewFunc_results{},
			}
			r.mock.resultsByParams_NewFunc = append(r.mock.resultsByParams_NewFunc, *results)
			if insertAt != -1 && insertAt+1 < len(r.mock.resultsByParams_NewFunc) {
				copy(r.mock.resultsByParams_NewFunc[insertAt+1:], r.mock.resultsByParams_NewFunc[insertAt:0])
				r.mock.resultsByParams_NewFunc[insertAt] = *results
			}
		}

		var typeSpecUsed *dst.TypeSpec
		if r.anyParams&(1<<0) == 0 {
			typeSpecUsed = r.paramsKey.typeSpec
		}
		paramsKey := mockConverterer_NewFunc_paramsKey{
			typeSpec: typeSpecUsed,
		}

		var ok bool
		r.results, ok = results.results[paramsKey]
		if !ok {
			r.results = &mockConverterer_NewFunc_results{
				params:   r.params,
				results:  nil,
				index:    0,
				anyTimes: false,
			}
			results.results[paramsKey] = r.results
		}
	}
}

func (r *mockConverterer_NewFunc_fnRecorder) times(count int) *mockConverterer_NewFunc_fnRecorder {
	if r.results == nil {
		r.mock.scene.MoqT.Fatalf("returnResults or doReturnResults must be called before calling times")
		return nil
	}
	last := r.results.results[len(r.results.results)-1]
	for n := 0; n < count-1; n++ {
		if last.sequence != 0 {
			last = struct {
				values     *struct{ funcDecl *dst.FuncDecl }
				sequence   uint32
				doFn       mockConverterer_NewFunc_doFn
				doReturnFn mockConverterer_NewFunc_doReturnFn
			}{
				values: &struct{ funcDecl *dst.FuncDecl }{
					funcDecl: last.values.funcDecl,
				},
				sequence: r.mock.scene.NextRecorderSequence(),
			}
		}
		r.results.results = append(r.results.results, last)
	}
	return r
}

func (r *mockConverterer_NewFunc_fnRecorder) anyTimes() {
	if r.results == nil {
		r.mock.scene.MoqT.Fatalf("returnResults or doReturnResults must be called before calling anyTimes")
		return
	}
	r.results.anyTimes = true
}

func (m *mockConverterer_recorder) IsolationAccessor(typeName, suffix, fnName string) *mockConverterer_IsolationAccessor_fnRecorder {
	return &mockConverterer_IsolationAccessor_fnRecorder{
		params: mockConverterer_IsolationAccessor_params{
			typeName: typeName,
			suffix:   suffix,
			fnName:   fnName,
		},
		paramsKey: mockConverterer_IsolationAccessor_paramsKey{
			typeName: typeName,
			suffix:   suffix,
			fnName:   fnName,
		},
		sequence: m.mock.config.Sequence == moq.SeqDefaultOn,
		mock:     m.mock,
	}
}

func (r *mockConverterer_IsolationAccessor_fnRecorder) anyTypeName() *mockConverterer_IsolationAccessor_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("Any functions must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.anyParams |= 1 << 0
	return r
}

func (r *mockConverterer_IsolationAccessor_fnRecorder) anySuffix() *mockConverterer_IsolationAccessor_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("Any functions must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.anyParams |= 1 << 1
	return r
}

func (r *mockConverterer_IsolationAccessor_fnRecorder) anyFnName() *mockConverterer_IsolationAccessor_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("Any functions must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.anyParams |= 1 << 2
	return r
}

func (r *mockConverterer_IsolationAccessor_fnRecorder) seq() *mockConverterer_IsolationAccessor_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("seq must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.sequence = true
	return r
}

func (r *mockConverterer_IsolationAccessor_fnRecorder) noSeq() *mockConverterer_IsolationAccessor_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("noSeq must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.sequence = false
	return r
}

func (r *mockConverterer_IsolationAccessor_fnRecorder) returnResults(funcDecl *dst.FuncDecl) *mockConverterer_IsolationAccessor_fnRecorder {
	r.findResults()

	var sequence uint32
	if r.sequence {
		sequence = r.mock.scene.NextRecorderSequence()
	}

	r.results.results = append(r.results.results, struct {
		values     *struct{ funcDecl *dst.FuncDecl }
		sequence   uint32
		doFn       mockConverterer_IsolationAccessor_doFn
		doReturnFn mockConverterer_IsolationAccessor_doReturnFn
	}{
		values: &struct{ funcDecl *dst.FuncDecl }{
			funcDecl: funcDecl,
		},
		sequence: sequence,
	})
	return r
}

func (r *mockConverterer_IsolationAccessor_fnRecorder) andDo(fn mockConverterer_IsolationAccessor_doFn) *mockConverterer_IsolationAccessor_fnRecorder {
	if r.results == nil {
		r.mock.scene.MoqT.Fatalf("returnResults must be called before calling andDo")
		return nil
	}
	last := &r.results.results[len(r.results.results)-1]
	last.doFn = fn
	return r
}

func (r *mockConverterer_IsolationAccessor_fnRecorder) doReturnResults(fn mockConverterer_IsolationAccessor_doReturnFn) *mockConverterer_IsolationAccessor_fnRecorder {
	r.findResults()

	var sequence uint32
	if r.sequence {
		sequence = r.mock.scene.NextRecorderSequence()
	}

	r.results.results = append(r.results.results, struct {
		values     *struct{ funcDecl *dst.FuncDecl }
		sequence   uint32
		doFn       mockConverterer_IsolationAccessor_doFn
		doReturnFn mockConverterer_IsolationAccessor_doReturnFn
	}{sequence: sequence, doReturnFn: fn})
	return r
}

func (r *mockConverterer_IsolationAccessor_fnRecorder) findResults() {
	if r.results == nil {
		anyCount := bits.OnesCount64(r.anyParams)
		insertAt := -1
		var results *mockConverterer_IsolationAccessor_resultsByParams
		for n, res := range r.mock.resultsByParams_IsolationAccessor {
			if res.anyParams == r.anyParams {
				results = &res
				break
			}
			if res.anyCount > anyCount {
				insertAt = n
			}
		}
		if results == nil {
			results = &mockConverterer_IsolationAccessor_resultsByParams{
				anyCount:  anyCount,
				anyParams: r.anyParams,
				results:   map[mockConverterer_IsolationAccessor_paramsKey]*mockConverterer_IsolationAccessor_results{},
			}
			r.mock.resultsByParams_IsolationAccessor = append(r.mock.resultsByParams_IsolationAccessor, *results)
			if insertAt != -1 && insertAt+1 < len(r.mock.resultsByParams_IsolationAccessor) {
				copy(r.mock.resultsByParams_IsolationAccessor[insertAt+1:], r.mock.resultsByParams_IsolationAccessor[insertAt:0])
				r.mock.resultsByParams_IsolationAccessor[insertAt] = *results
			}
		}

		var typeNameUsed string
		if r.anyParams&(1<<0) == 0 {
			typeNameUsed = r.paramsKey.typeName
		}
		var suffixUsed string
		if r.anyParams&(1<<1) == 0 {
			suffixUsed = r.paramsKey.suffix
		}
		var fnNameUsed string
		if r.anyParams&(1<<2) == 0 {
			fnNameUsed = r.paramsKey.fnName
		}
		paramsKey := mockConverterer_IsolationAccessor_paramsKey{
			typeName: typeNameUsed,
			suffix:   suffixUsed,
			fnName:   fnNameUsed,
		}

		var ok bool
		r.results, ok = results.results[paramsKey]
		if !ok {
			r.results = &mockConverterer_IsolationAccessor_results{
				params:   r.params,
				results:  nil,
				index:    0,
				anyTimes: false,
			}
			results.results[paramsKey] = r.results
		}
	}
}

func (r *mockConverterer_IsolationAccessor_fnRecorder) times(count int) *mockConverterer_IsolationAccessor_fnRecorder {
	if r.results == nil {
		r.mock.scene.MoqT.Fatalf("returnResults or doReturnResults must be called before calling times")
		return nil
	}
	last := r.results.results[len(r.results.results)-1]
	for n := 0; n < count-1; n++ {
		if last.sequence != 0 {
			last = struct {
				values     *struct{ funcDecl *dst.FuncDecl }
				sequence   uint32
				doFn       mockConverterer_IsolationAccessor_doFn
				doReturnFn mockConverterer_IsolationAccessor_doReturnFn
			}{
				values: &struct{ funcDecl *dst.FuncDecl }{
					funcDecl: last.values.funcDecl,
				},
				sequence: r.mock.scene.NextRecorderSequence(),
			}
		}
		r.results.results = append(r.results.results, last)
	}
	return r
}

func (r *mockConverterer_IsolationAccessor_fnRecorder) anyTimes() {
	if r.results == nil {
		r.mock.scene.MoqT.Fatalf("returnResults or doReturnResults must be called before calling anyTimes")
		return
	}
	r.results.anyTimes = true
}

func (m *mockConverterer_recorder) FuncClosure(typeName, pkgPath string, fn generator.Func) *mockConverterer_FuncClosure_fnRecorder {
	return &mockConverterer_FuncClosure_fnRecorder{
		params: mockConverterer_FuncClosure_params{
			typeName: typeName,
			pkgPath:  pkgPath,
			fn:       fn,
		},
		paramsKey: mockConverterer_FuncClosure_paramsKey{
			typeName: typeName,
			pkgPath:  pkgPath,
			fn:       fn,
		},
		sequence: m.mock.config.Sequence == moq.SeqDefaultOn,
		mock:     m.mock,
	}
}

func (r *mockConverterer_FuncClosure_fnRecorder) anyTypeName() *mockConverterer_FuncClosure_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("Any functions must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.anyParams |= 1 << 0
	return r
}

func (r *mockConverterer_FuncClosure_fnRecorder) anyPkgPath() *mockConverterer_FuncClosure_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("Any functions must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.anyParams |= 1 << 1
	return r
}

func (r *mockConverterer_FuncClosure_fnRecorder) anyFn() *mockConverterer_FuncClosure_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("Any functions must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.anyParams |= 1 << 2
	return r
}

func (r *mockConverterer_FuncClosure_fnRecorder) seq() *mockConverterer_FuncClosure_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("seq must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.sequence = true
	return r
}

func (r *mockConverterer_FuncClosure_fnRecorder) noSeq() *mockConverterer_FuncClosure_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("noSeq must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.sequence = false
	return r
}

func (r *mockConverterer_FuncClosure_fnRecorder) returnResults(funcDecl *dst.FuncDecl) *mockConverterer_FuncClosure_fnRecorder {
	r.findResults()

	var sequence uint32
	if r.sequence {
		sequence = r.mock.scene.NextRecorderSequence()
	}

	r.results.results = append(r.results.results, struct {
		values     *struct{ funcDecl *dst.FuncDecl }
		sequence   uint32
		doFn       mockConverterer_FuncClosure_doFn
		doReturnFn mockConverterer_FuncClosure_doReturnFn
	}{
		values: &struct{ funcDecl *dst.FuncDecl }{
			funcDecl: funcDecl,
		},
		sequence: sequence,
	})
	return r
}

func (r *mockConverterer_FuncClosure_fnRecorder) andDo(fn mockConverterer_FuncClosure_doFn) *mockConverterer_FuncClosure_fnRecorder {
	if r.results == nil {
		r.mock.scene.MoqT.Fatalf("returnResults must be called before calling andDo")
		return nil
	}
	last := &r.results.results[len(r.results.results)-1]
	last.doFn = fn
	return r
}

func (r *mockConverterer_FuncClosure_fnRecorder) doReturnResults(fn mockConverterer_FuncClosure_doReturnFn) *mockConverterer_FuncClosure_fnRecorder {
	r.findResults()

	var sequence uint32
	if r.sequence {
		sequence = r.mock.scene.NextRecorderSequence()
	}

	r.results.results = append(r.results.results, struct {
		values     *struct{ funcDecl *dst.FuncDecl }
		sequence   uint32
		doFn       mockConverterer_FuncClosure_doFn
		doReturnFn mockConverterer_FuncClosure_doReturnFn
	}{sequence: sequence, doReturnFn: fn})
	return r
}

func (r *mockConverterer_FuncClosure_fnRecorder) findResults() {
	if r.results == nil {
		anyCount := bits.OnesCount64(r.anyParams)
		insertAt := -1
		var results *mockConverterer_FuncClosure_resultsByParams
		for n, res := range r.mock.resultsByParams_FuncClosure {
			if res.anyParams == r.anyParams {
				results = &res
				break
			}
			if res.anyCount > anyCount {
				insertAt = n
			}
		}
		if results == nil {
			results = &mockConverterer_FuncClosure_resultsByParams{
				anyCount:  anyCount,
				anyParams: r.anyParams,
				results:   map[mockConverterer_FuncClosure_paramsKey]*mockConverterer_FuncClosure_results{},
			}
			r.mock.resultsByParams_FuncClosure = append(r.mock.resultsByParams_FuncClosure, *results)
			if insertAt != -1 && insertAt+1 < len(r.mock.resultsByParams_FuncClosure) {
				copy(r.mock.resultsByParams_FuncClosure[insertAt+1:], r.mock.resultsByParams_FuncClosure[insertAt:0])
				r.mock.resultsByParams_FuncClosure[insertAt] = *results
			}
		}

		var typeNameUsed string
		if r.anyParams&(1<<0) == 0 {
			typeNameUsed = r.paramsKey.typeName
		}
		var pkgPathUsed string
		if r.anyParams&(1<<1) == 0 {
			pkgPathUsed = r.paramsKey.pkgPath
		}
		var fnUsed generator.Func
		if r.anyParams&(1<<2) == 0 {
			fnUsed = r.paramsKey.fn
		}
		paramsKey := mockConverterer_FuncClosure_paramsKey{
			typeName: typeNameUsed,
			pkgPath:  pkgPathUsed,
			fn:       fnUsed,
		}

		var ok bool
		r.results, ok = results.results[paramsKey]
		if !ok {
			r.results = &mockConverterer_FuncClosure_results{
				params:   r.params,
				results:  nil,
				index:    0,
				anyTimes: false,
			}
			results.results[paramsKey] = r.results
		}
	}
}

func (r *mockConverterer_FuncClosure_fnRecorder) times(count int) *mockConverterer_FuncClosure_fnRecorder {
	if r.results == nil {
		r.mock.scene.MoqT.Fatalf("returnResults or doReturnResults must be called before calling times")
		return nil
	}
	last := r.results.results[len(r.results.results)-1]
	for n := 0; n < count-1; n++ {
		if last.sequence != 0 {
			last = struct {
				values     *struct{ funcDecl *dst.FuncDecl }
				sequence   uint32
				doFn       mockConverterer_FuncClosure_doFn
				doReturnFn mockConverterer_FuncClosure_doReturnFn
			}{
				values: &struct{ funcDecl *dst.FuncDecl }{
					funcDecl: last.values.funcDecl,
				},
				sequence: r.mock.scene.NextRecorderSequence(),
			}
		}
		r.results.results = append(r.results.results, last)
	}
	return r
}

func (r *mockConverterer_FuncClosure_fnRecorder) anyTimes() {
	if r.results == nil {
		r.mock.scene.MoqT.Fatalf("returnResults or doReturnResults must be called before calling anyTimes")
		return
	}
	r.results.anyTimes = true
}

func (m *mockConverterer_recorder) MockMethod(typeName string, fn generator.Func) *mockConverterer_MockMethod_fnRecorder {
	return &mockConverterer_MockMethod_fnRecorder{
		params: mockConverterer_MockMethod_params{
			typeName: typeName,
			fn:       fn,
		},
		paramsKey: mockConverterer_MockMethod_paramsKey{
			typeName: typeName,
			fn:       fn,
		},
		sequence: m.mock.config.Sequence == moq.SeqDefaultOn,
		mock:     m.mock,
	}
}

func (r *mockConverterer_MockMethod_fnRecorder) anyTypeName() *mockConverterer_MockMethod_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("Any functions must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.anyParams |= 1 << 0
	return r
}

func (r *mockConverterer_MockMethod_fnRecorder) anyFn() *mockConverterer_MockMethod_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("Any functions must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.anyParams |= 1 << 1
	return r
}

func (r *mockConverterer_MockMethod_fnRecorder) seq() *mockConverterer_MockMethod_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("seq must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.sequence = true
	return r
}

func (r *mockConverterer_MockMethod_fnRecorder) noSeq() *mockConverterer_MockMethod_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("noSeq must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.sequence = false
	return r
}

func (r *mockConverterer_MockMethod_fnRecorder) returnResults(funcDecl *dst.FuncDecl) *mockConverterer_MockMethod_fnRecorder {
	r.findResults()

	var sequence uint32
	if r.sequence {
		sequence = r.mock.scene.NextRecorderSequence()
	}

	r.results.results = append(r.results.results, struct {
		values     *struct{ funcDecl *dst.FuncDecl }
		sequence   uint32
		doFn       mockConverterer_MockMethod_doFn
		doReturnFn mockConverterer_MockMethod_doReturnFn
	}{
		values: &struct{ funcDecl *dst.FuncDecl }{
			funcDecl: funcDecl,
		},
		sequence: sequence,
	})
	return r
}

func (r *mockConverterer_MockMethod_fnRecorder) andDo(fn mockConverterer_MockMethod_doFn) *mockConverterer_MockMethod_fnRecorder {
	if r.results == nil {
		r.mock.scene.MoqT.Fatalf("returnResults must be called before calling andDo")
		return nil
	}
	last := &r.results.results[len(r.results.results)-1]
	last.doFn = fn
	return r
}

func (r *mockConverterer_MockMethod_fnRecorder) doReturnResults(fn mockConverterer_MockMethod_doReturnFn) *mockConverterer_MockMethod_fnRecorder {
	r.findResults()

	var sequence uint32
	if r.sequence {
		sequence = r.mock.scene.NextRecorderSequence()
	}

	r.results.results = append(r.results.results, struct {
		values     *struct{ funcDecl *dst.FuncDecl }
		sequence   uint32
		doFn       mockConverterer_MockMethod_doFn
		doReturnFn mockConverterer_MockMethod_doReturnFn
	}{sequence: sequence, doReturnFn: fn})
	return r
}

func (r *mockConverterer_MockMethod_fnRecorder) findResults() {
	if r.results == nil {
		anyCount := bits.OnesCount64(r.anyParams)
		insertAt := -1
		var results *mockConverterer_MockMethod_resultsByParams
		for n, res := range r.mock.resultsByParams_MockMethod {
			if res.anyParams == r.anyParams {
				results = &res
				break
			}
			if res.anyCount > anyCount {
				insertAt = n
			}
		}
		if results == nil {
			results = &mockConverterer_MockMethod_resultsByParams{
				anyCount:  anyCount,
				anyParams: r.anyParams,
				results:   map[mockConverterer_MockMethod_paramsKey]*mockConverterer_MockMethod_results{},
			}
			r.mock.resultsByParams_MockMethod = append(r.mock.resultsByParams_MockMethod, *results)
			if insertAt != -1 && insertAt+1 < len(r.mock.resultsByParams_MockMethod) {
				copy(r.mock.resultsByParams_MockMethod[insertAt+1:], r.mock.resultsByParams_MockMethod[insertAt:0])
				r.mock.resultsByParams_MockMethod[insertAt] = *results
			}
		}

		var typeNameUsed string
		if r.anyParams&(1<<0) == 0 {
			typeNameUsed = r.paramsKey.typeName
		}
		var fnUsed generator.Func
		if r.anyParams&(1<<1) == 0 {
			fnUsed = r.paramsKey.fn
		}
		paramsKey := mockConverterer_MockMethod_paramsKey{
			typeName: typeNameUsed,
			fn:       fnUsed,
		}

		var ok bool
		r.results, ok = results.results[paramsKey]
		if !ok {
			r.results = &mockConverterer_MockMethod_results{
				params:   r.params,
				results:  nil,
				index:    0,
				anyTimes: false,
			}
			results.results[paramsKey] = r.results
		}
	}
}

func (r *mockConverterer_MockMethod_fnRecorder) times(count int) *mockConverterer_MockMethod_fnRecorder {
	if r.results == nil {
		r.mock.scene.MoqT.Fatalf("returnResults or doReturnResults must be called before calling times")
		return nil
	}
	last := r.results.results[len(r.results.results)-1]
	for n := 0; n < count-1; n++ {
		if last.sequence != 0 {
			last = struct {
				values     *struct{ funcDecl *dst.FuncDecl }
				sequence   uint32
				doFn       mockConverterer_MockMethod_doFn
				doReturnFn mockConverterer_MockMethod_doReturnFn
			}{
				values: &struct{ funcDecl *dst.FuncDecl }{
					funcDecl: last.values.funcDecl,
				},
				sequence: r.mock.scene.NextRecorderSequence(),
			}
		}
		r.results.results = append(r.results.results, last)
	}
	return r
}

func (r *mockConverterer_MockMethod_fnRecorder) anyTimes() {
	if r.results == nil {
		r.mock.scene.MoqT.Fatalf("returnResults or doReturnResults must be called before calling anyTimes")
		return
	}
	r.results.anyTimes = true
}

func (m *mockConverterer_recorder) RecorderMethods(typeName string, fn generator.Func) *mockConverterer_RecorderMethods_fnRecorder {
	return &mockConverterer_RecorderMethods_fnRecorder{
		params: mockConverterer_RecorderMethods_params{
			typeName: typeName,
			fn:       fn,
		},
		paramsKey: mockConverterer_RecorderMethods_paramsKey{
			typeName: typeName,
			fn:       fn,
		},
		sequence: m.mock.config.Sequence == moq.SeqDefaultOn,
		mock:     m.mock,
	}
}

func (r *mockConverterer_RecorderMethods_fnRecorder) anyTypeName() *mockConverterer_RecorderMethods_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("Any functions must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.anyParams |= 1 << 0
	return r
}

func (r *mockConverterer_RecorderMethods_fnRecorder) anyFn() *mockConverterer_RecorderMethods_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("Any functions must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.anyParams |= 1 << 1
	return r
}

func (r *mockConverterer_RecorderMethods_fnRecorder) seq() *mockConverterer_RecorderMethods_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("seq must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.sequence = true
	return r
}

func (r *mockConverterer_RecorderMethods_fnRecorder) noSeq() *mockConverterer_RecorderMethods_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("noSeq must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.sequence = false
	return r
}

func (r *mockConverterer_RecorderMethods_fnRecorder) returnResults(funcDecls []dst.Decl) *mockConverterer_RecorderMethods_fnRecorder {
	r.findResults()

	var sequence uint32
	if r.sequence {
		sequence = r.mock.scene.NextRecorderSequence()
	}

	r.results.results = append(r.results.results, struct {
		values     *struct{ funcDecls []dst.Decl }
		sequence   uint32
		doFn       mockConverterer_RecorderMethods_doFn
		doReturnFn mockConverterer_RecorderMethods_doReturnFn
	}{
		values: &struct{ funcDecls []dst.Decl }{
			funcDecls: funcDecls,
		},
		sequence: sequence,
	})
	return r
}

func (r *mockConverterer_RecorderMethods_fnRecorder) andDo(fn mockConverterer_RecorderMethods_doFn) *mockConverterer_RecorderMethods_fnRecorder {
	if r.results == nil {
		r.mock.scene.MoqT.Fatalf("returnResults must be called before calling andDo")
		return nil
	}
	last := &r.results.results[len(r.results.results)-1]
	last.doFn = fn
	return r
}

func (r *mockConverterer_RecorderMethods_fnRecorder) doReturnResults(fn mockConverterer_RecorderMethods_doReturnFn) *mockConverterer_RecorderMethods_fnRecorder {
	r.findResults()

	var sequence uint32
	if r.sequence {
		sequence = r.mock.scene.NextRecorderSequence()
	}

	r.results.results = append(r.results.results, struct {
		values     *struct{ funcDecls []dst.Decl }
		sequence   uint32
		doFn       mockConverterer_RecorderMethods_doFn
		doReturnFn mockConverterer_RecorderMethods_doReturnFn
	}{sequence: sequence, doReturnFn: fn})
	return r
}

func (r *mockConverterer_RecorderMethods_fnRecorder) findResults() {
	if r.results == nil {
		anyCount := bits.OnesCount64(r.anyParams)
		insertAt := -1
		var results *mockConverterer_RecorderMethods_resultsByParams
		for n, res := range r.mock.resultsByParams_RecorderMethods {
			if res.anyParams == r.anyParams {
				results = &res
				break
			}
			if res.anyCount > anyCount {
				insertAt = n
			}
		}
		if results == nil {
			results = &mockConverterer_RecorderMethods_resultsByParams{
				anyCount:  anyCount,
				anyParams: r.anyParams,
				results:   map[mockConverterer_RecorderMethods_paramsKey]*mockConverterer_RecorderMethods_results{},
			}
			r.mock.resultsByParams_RecorderMethods = append(r.mock.resultsByParams_RecorderMethods, *results)
			if insertAt != -1 && insertAt+1 < len(r.mock.resultsByParams_RecorderMethods) {
				copy(r.mock.resultsByParams_RecorderMethods[insertAt+1:], r.mock.resultsByParams_RecorderMethods[insertAt:0])
				r.mock.resultsByParams_RecorderMethods[insertAt] = *results
			}
		}

		var typeNameUsed string
		if r.anyParams&(1<<0) == 0 {
			typeNameUsed = r.paramsKey.typeName
		}
		var fnUsed generator.Func
		if r.anyParams&(1<<1) == 0 {
			fnUsed = r.paramsKey.fn
		}
		paramsKey := mockConverterer_RecorderMethods_paramsKey{
			typeName: typeNameUsed,
			fn:       fnUsed,
		}

		var ok bool
		r.results, ok = results.results[paramsKey]
		if !ok {
			r.results = &mockConverterer_RecorderMethods_results{
				params:   r.params,
				results:  nil,
				index:    0,
				anyTimes: false,
			}
			results.results[paramsKey] = r.results
		}
	}
}

func (r *mockConverterer_RecorderMethods_fnRecorder) times(count int) *mockConverterer_RecorderMethods_fnRecorder {
	if r.results == nil {
		r.mock.scene.MoqT.Fatalf("returnResults or doReturnResults must be called before calling times")
		return nil
	}
	last := r.results.results[len(r.results.results)-1]
	for n := 0; n < count-1; n++ {
		if last.sequence != 0 {
			last = struct {
				values     *struct{ funcDecls []dst.Decl }
				sequence   uint32
				doFn       mockConverterer_RecorderMethods_doFn
				doReturnFn mockConverterer_RecorderMethods_doReturnFn
			}{
				values: &struct{ funcDecls []dst.Decl }{
					funcDecls: last.values.funcDecls,
				},
				sequence: r.mock.scene.NextRecorderSequence(),
			}
		}
		r.results.results = append(r.results.results, last)
	}
	return r
}

func (r *mockConverterer_RecorderMethods_fnRecorder) anyTimes() {
	if r.results == nil {
		r.mock.scene.MoqT.Fatalf("returnResults or doReturnResults must be called before calling anyTimes")
		return
	}
	r.results.anyTimes = true
}

func (m *mockConverterer_recorder) ResetMethod(typeSpec *dst.TypeSpec, funcs []generator.Func) *mockConverterer_ResetMethod_fnRecorder {
	return &mockConverterer_ResetMethod_fnRecorder{
		params: mockConverterer_ResetMethod_params{
			typeSpec: typeSpec,
			funcs:    funcs,
		},
		paramsKey: mockConverterer_ResetMethod_paramsKey{
			typeSpec: typeSpec,
			funcs:    hash.DeepHash(funcs),
		},
		sequence: m.mock.config.Sequence == moq.SeqDefaultOn,
		mock:     m.mock,
	}
}

func (r *mockConverterer_ResetMethod_fnRecorder) anyTypeSpec() *mockConverterer_ResetMethod_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("Any functions must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.anyParams |= 1 << 0
	return r
}

func (r *mockConverterer_ResetMethod_fnRecorder) anyFuncs() *mockConverterer_ResetMethod_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("Any functions must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.anyParams |= 1 << 1
	return r
}

func (r *mockConverterer_ResetMethod_fnRecorder) seq() *mockConverterer_ResetMethod_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("seq must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.sequence = true
	return r
}

func (r *mockConverterer_ResetMethod_fnRecorder) noSeq() *mockConverterer_ResetMethod_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("noSeq must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.sequence = false
	return r
}

func (r *mockConverterer_ResetMethod_fnRecorder) returnResults(funcDecl *dst.FuncDecl) *mockConverterer_ResetMethod_fnRecorder {
	r.findResults()

	var sequence uint32
	if r.sequence {
		sequence = r.mock.scene.NextRecorderSequence()
	}

	r.results.results = append(r.results.results, struct {
		values     *struct{ funcDecl *dst.FuncDecl }
		sequence   uint32
		doFn       mockConverterer_ResetMethod_doFn
		doReturnFn mockConverterer_ResetMethod_doReturnFn
	}{
		values: &struct{ funcDecl *dst.FuncDecl }{
			funcDecl: funcDecl,
		},
		sequence: sequence,
	})
	return r
}

func (r *mockConverterer_ResetMethod_fnRecorder) andDo(fn mockConverterer_ResetMethod_doFn) *mockConverterer_ResetMethod_fnRecorder {
	if r.results == nil {
		r.mock.scene.MoqT.Fatalf("returnResults must be called before calling andDo")
		return nil
	}
	last := &r.results.results[len(r.results.results)-1]
	last.doFn = fn
	return r
}

func (r *mockConverterer_ResetMethod_fnRecorder) doReturnResults(fn mockConverterer_ResetMethod_doReturnFn) *mockConverterer_ResetMethod_fnRecorder {
	r.findResults()

	var sequence uint32
	if r.sequence {
		sequence = r.mock.scene.NextRecorderSequence()
	}

	r.results.results = append(r.results.results, struct {
		values     *struct{ funcDecl *dst.FuncDecl }
		sequence   uint32
		doFn       mockConverterer_ResetMethod_doFn
		doReturnFn mockConverterer_ResetMethod_doReturnFn
	}{sequence: sequence, doReturnFn: fn})
	return r
}

func (r *mockConverterer_ResetMethod_fnRecorder) findResults() {
	if r.results == nil {
		anyCount := bits.OnesCount64(r.anyParams)
		insertAt := -1
		var results *mockConverterer_ResetMethod_resultsByParams
		for n, res := range r.mock.resultsByParams_ResetMethod {
			if res.anyParams == r.anyParams {
				results = &res
				break
			}
			if res.anyCount > anyCount {
				insertAt = n
			}
		}
		if results == nil {
			results = &mockConverterer_ResetMethod_resultsByParams{
				anyCount:  anyCount,
				anyParams: r.anyParams,
				results:   map[mockConverterer_ResetMethod_paramsKey]*mockConverterer_ResetMethod_results{},
			}
			r.mock.resultsByParams_ResetMethod = append(r.mock.resultsByParams_ResetMethod, *results)
			if insertAt != -1 && insertAt+1 < len(r.mock.resultsByParams_ResetMethod) {
				copy(r.mock.resultsByParams_ResetMethod[insertAt+1:], r.mock.resultsByParams_ResetMethod[insertAt:0])
				r.mock.resultsByParams_ResetMethod[insertAt] = *results
			}
		}

		var typeSpecUsed *dst.TypeSpec
		if r.anyParams&(1<<0) == 0 {
			typeSpecUsed = r.paramsKey.typeSpec
		}
		var funcsUsed hash.Hash
		if r.anyParams&(1<<1) == 0 {
			funcsUsed = r.paramsKey.funcs
		}
		paramsKey := mockConverterer_ResetMethod_paramsKey{
			typeSpec: typeSpecUsed,
			funcs:    funcsUsed,
		}

		var ok bool
		r.results, ok = results.results[paramsKey]
		if !ok {
			r.results = &mockConverterer_ResetMethod_results{
				params:   r.params,
				results:  nil,
				index:    0,
				anyTimes: false,
			}
			results.results[paramsKey] = r.results
		}
	}
}

func (r *mockConverterer_ResetMethod_fnRecorder) times(count int) *mockConverterer_ResetMethod_fnRecorder {
	if r.results == nil {
		r.mock.scene.MoqT.Fatalf("returnResults or doReturnResults must be called before calling times")
		return nil
	}
	last := r.results.results[len(r.results.results)-1]
	for n := 0; n < count-1; n++ {
		if last.sequence != 0 {
			last = struct {
				values     *struct{ funcDecl *dst.FuncDecl }
				sequence   uint32
				doFn       mockConverterer_ResetMethod_doFn
				doReturnFn mockConverterer_ResetMethod_doReturnFn
			}{
				values: &struct{ funcDecl *dst.FuncDecl }{
					funcDecl: last.values.funcDecl,
				},
				sequence: r.mock.scene.NextRecorderSequence(),
			}
		}
		r.results.results = append(r.results.results, last)
	}
	return r
}

func (r *mockConverterer_ResetMethod_fnRecorder) anyTimes() {
	if r.results == nil {
		r.mock.scene.MoqT.Fatalf("returnResults or doReturnResults must be called before calling anyTimes")
		return
	}
	r.results.anyTimes = true
}

func (m *mockConverterer_recorder) AssertMethod(typeSpec *dst.TypeSpec, funcs []generator.Func) *mockConverterer_AssertMethod_fnRecorder {
	return &mockConverterer_AssertMethod_fnRecorder{
		params: mockConverterer_AssertMethod_params{
			typeSpec: typeSpec,
			funcs:    funcs,
		},
		paramsKey: mockConverterer_AssertMethod_paramsKey{
			typeSpec: typeSpec,
			funcs:    hash.DeepHash(funcs),
		},
		sequence: m.mock.config.Sequence == moq.SeqDefaultOn,
		mock:     m.mock,
	}
}

func (r *mockConverterer_AssertMethod_fnRecorder) anyTypeSpec() *mockConverterer_AssertMethod_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("Any functions must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.anyParams |= 1 << 0
	return r
}

func (r *mockConverterer_AssertMethod_fnRecorder) anyFuncs() *mockConverterer_AssertMethod_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("Any functions must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.anyParams |= 1 << 1
	return r
}

func (r *mockConverterer_AssertMethod_fnRecorder) seq() *mockConverterer_AssertMethod_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("seq must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.sequence = true
	return r
}

func (r *mockConverterer_AssertMethod_fnRecorder) noSeq() *mockConverterer_AssertMethod_fnRecorder {
	if r.results != nil {
		r.mock.scene.MoqT.Fatalf("noSeq must be called before returnResults or doReturnResults calls, parameters: %#v", r.params)
		return nil
	}
	r.sequence = false
	return r
}

func (r *mockConverterer_AssertMethod_fnRecorder) returnResults(funcDecl *dst.FuncDecl) *mockConverterer_AssertMethod_fnRecorder {
	r.findResults()

	var sequence uint32
	if r.sequence {
		sequence = r.mock.scene.NextRecorderSequence()
	}

	r.results.results = append(r.results.results, struct {
		values     *struct{ funcDecl *dst.FuncDecl }
		sequence   uint32
		doFn       mockConverterer_AssertMethod_doFn
		doReturnFn mockConverterer_AssertMethod_doReturnFn
	}{
		values: &struct{ funcDecl *dst.FuncDecl }{
			funcDecl: funcDecl,
		},
		sequence: sequence,
	})
	return r
}

func (r *mockConverterer_AssertMethod_fnRecorder) andDo(fn mockConverterer_AssertMethod_doFn) *mockConverterer_AssertMethod_fnRecorder {
	if r.results == nil {
		r.mock.scene.MoqT.Fatalf("returnResults must be called before calling andDo")
		return nil
	}
	last := &r.results.results[len(r.results.results)-1]
	last.doFn = fn
	return r
}

func (r *mockConverterer_AssertMethod_fnRecorder) doReturnResults(fn mockConverterer_AssertMethod_doReturnFn) *mockConverterer_AssertMethod_fnRecorder {
	r.findResults()

	var sequence uint32
	if r.sequence {
		sequence = r.mock.scene.NextRecorderSequence()
	}

	r.results.results = append(r.results.results, struct {
		values     *struct{ funcDecl *dst.FuncDecl }
		sequence   uint32
		doFn       mockConverterer_AssertMethod_doFn
		doReturnFn mockConverterer_AssertMethod_doReturnFn
	}{sequence: sequence, doReturnFn: fn})
	return r
}

func (r *mockConverterer_AssertMethod_fnRecorder) findResults() {
	if r.results == nil {
		anyCount := bits.OnesCount64(r.anyParams)
		insertAt := -1
		var results *mockConverterer_AssertMethod_resultsByParams
		for n, res := range r.mock.resultsByParams_AssertMethod {
			if res.anyParams == r.anyParams {
				results = &res
				break
			}
			if res.anyCount > anyCount {
				insertAt = n
			}
		}
		if results == nil {
			results = &mockConverterer_AssertMethod_resultsByParams{
				anyCount:  anyCount,
				anyParams: r.anyParams,
				results:   map[mockConverterer_AssertMethod_paramsKey]*mockConverterer_AssertMethod_results{},
			}
			r.mock.resultsByParams_AssertMethod = append(r.mock.resultsByParams_AssertMethod, *results)
			if insertAt != -1 && insertAt+1 < len(r.mock.resultsByParams_AssertMethod) {
				copy(r.mock.resultsByParams_AssertMethod[insertAt+1:], r.mock.resultsByParams_AssertMethod[insertAt:0])
				r.mock.resultsByParams_AssertMethod[insertAt] = *results
			}
		}

		var typeSpecUsed *dst.TypeSpec
		if r.anyParams&(1<<0) == 0 {
			typeSpecUsed = r.paramsKey.typeSpec
		}
		var funcsUsed hash.Hash
		if r.anyParams&(1<<1) == 0 {
			funcsUsed = r.paramsKey.funcs
		}
		paramsKey := mockConverterer_AssertMethod_paramsKey{
			typeSpec: typeSpecUsed,
			funcs:    funcsUsed,
		}

		var ok bool
		r.results, ok = results.results[paramsKey]
		if !ok {
			r.results = &mockConverterer_AssertMethod_results{
				params:   r.params,
				results:  nil,
				index:    0,
				anyTimes: false,
			}
			results.results[paramsKey] = r.results
		}
	}
}

func (r *mockConverterer_AssertMethod_fnRecorder) times(count int) *mockConverterer_AssertMethod_fnRecorder {
	if r.results == nil {
		r.mock.scene.MoqT.Fatalf("returnResults or doReturnResults must be called before calling times")
		return nil
	}
	last := r.results.results[len(r.results.results)-1]
	for n := 0; n < count-1; n++ {
		if last.sequence != 0 {
			last = struct {
				values     *struct{ funcDecl *dst.FuncDecl }
				sequence   uint32
				doFn       mockConverterer_AssertMethod_doFn
				doReturnFn mockConverterer_AssertMethod_doReturnFn
			}{
				values: &struct{ funcDecl *dst.FuncDecl }{
					funcDecl: last.values.funcDecl,
				},
				sequence: r.mock.scene.NextRecorderSequence(),
			}
		}
		r.results.results = append(r.results.results, last)
	}
	return r
}

func (r *mockConverterer_AssertMethod_fnRecorder) anyTimes() {
	if r.results == nil {
		r.mock.scene.MoqT.Fatalf("returnResults or doReturnResults must be called before calling anyTimes")
		return
	}
	r.results.anyTimes = true
}

// Reset resets the state of the mock
func (m *mockConverterer) Reset() {
	m.resultsByParams_BaseStruct = nil
	m.resultsByParams_IsolationStruct = nil
	m.resultsByParams_MethodStructs = nil
	m.resultsByParams_NewFunc = nil
	m.resultsByParams_IsolationAccessor = nil
	m.resultsByParams_FuncClosure = nil
	m.resultsByParams_MockMethod = nil
	m.resultsByParams_RecorderMethods = nil
	m.resultsByParams_ResetMethod = nil
	m.resultsByParams_AssertMethod = nil
}

// AssertExpectationsMet asserts that all expectations have been met
func (m *mockConverterer) AssertExpectationsMet() {
	for _, res := range m.resultsByParams_BaseStruct {
		for _, results := range res.results {
			missing := len(results.results) - int(atomic.LoadUint32(&results.index))
			if missing == 1 && results.anyTimes == true {
				continue
			}
			if missing > 0 {
				m.scene.MoqT.Errorf("Expected %d additional call(s) with parameters %#v", missing, results.params)
			}
		}
	}
	for _, res := range m.resultsByParams_IsolationStruct {
		for _, results := range res.results {
			missing := len(results.results) - int(atomic.LoadUint32(&results.index))
			if missing == 1 && results.anyTimes == true {
				continue
			}
			if missing > 0 {
				m.scene.MoqT.Errorf("Expected %d additional call(s) with parameters %#v", missing, results.params)
			}
		}
	}
	for _, res := range m.resultsByParams_MethodStructs {
		for _, results := range res.results {
			missing := len(results.results) - int(atomic.LoadUint32(&results.index))
			if missing == 1 && results.anyTimes == true {
				continue
			}
			if missing > 0 {
				m.scene.MoqT.Errorf("Expected %d additional call(s) with parameters %#v", missing, results.params)
			}
		}
	}
	for _, res := range m.resultsByParams_NewFunc {
		for _, results := range res.results {
			missing := len(results.results) - int(atomic.LoadUint32(&results.index))
			if missing == 1 && results.anyTimes == true {
				continue
			}
			if missing > 0 {
				m.scene.MoqT.Errorf("Expected %d additional call(s) with parameters %#v", missing, results.params)
			}
		}
	}
	for _, res := range m.resultsByParams_IsolationAccessor {
		for _, results := range res.results {
			missing := len(results.results) - int(atomic.LoadUint32(&results.index))
			if missing == 1 && results.anyTimes == true {
				continue
			}
			if missing > 0 {
				m.scene.MoqT.Errorf("Expected %d additional call(s) with parameters %#v", missing, results.params)
			}
		}
	}
	for _, res := range m.resultsByParams_FuncClosure {
		for _, results := range res.results {
			missing := len(results.results) - int(atomic.LoadUint32(&results.index))
			if missing == 1 && results.anyTimes == true {
				continue
			}
			if missing > 0 {
				m.scene.MoqT.Errorf("Expected %d additional call(s) with parameters %#v", missing, results.params)
			}
		}
	}
	for _, res := range m.resultsByParams_MockMethod {
		for _, results := range res.results {
			missing := len(results.results) - int(atomic.LoadUint32(&results.index))
			if missing == 1 && results.anyTimes == true {
				continue
			}
			if missing > 0 {
				m.scene.MoqT.Errorf("Expected %d additional call(s) with parameters %#v", missing, results.params)
			}
		}
	}
	for _, res := range m.resultsByParams_RecorderMethods {
		for _, results := range res.results {
			missing := len(results.results) - int(atomic.LoadUint32(&results.index))
			if missing == 1 && results.anyTimes == true {
				continue
			}
			if missing > 0 {
				m.scene.MoqT.Errorf("Expected %d additional call(s) with parameters %#v", missing, results.params)
			}
		}
	}
	for _, res := range m.resultsByParams_ResetMethod {
		for _, results := range res.results {
			missing := len(results.results) - int(atomic.LoadUint32(&results.index))
			if missing == 1 && results.anyTimes == true {
				continue
			}
			if missing > 0 {
				m.scene.MoqT.Errorf("Expected %d additional call(s) with parameters %#v", missing, results.params)
			}
		}
	}
	for _, res := range m.resultsByParams_AssertMethod {
		for _, results := range res.results {
			missing := len(results.results) - int(atomic.LoadUint32(&results.index))
			if missing == 1 && results.anyTimes == true {
				continue
			}
			if missing > 0 {
				m.scene.MoqT.Errorf("Expected %d additional call(s) with parameters %#v", missing, results.params)
			}
		}
	}
}
